<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/2/23
 * Time: 10:40
 * Note:
 */

namespace app\plugins\integral\forms\mall;


use app\core\ApiCode;
use app\helpers\DateHelper;
use app\helpers\IntegralLogHelper;
use app\helpers\ResponseHelper;
use app\models\BaseModel;

use app\plugins\integral\models\IntegralBirthdaySendLog;

class IntegralBirthdaySendForm extends BaseModel
{

    public $integral;
    public $uids;

    public function rules()
    {
        return [
            [['uids'], 'safe'],
            [['integral'], 'integer']
        ]; // TODO: Change the autogenerated stub
    }

    public function send()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }


        if (!$this->uids) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, '请选择用户');
        }

        $year = DateHelper::format(time(), 'Y');
        $i = 0;
        foreach ($this->uids as $uid) {
            $log = IntegralBirthdaySendLog::findOne(['year' => $year, 'user_id' => $uid, 'is_delete' => 0]);
            if (!$log) {
                $log = new IntegralBirthdaySendLog();
                $log->mall_id = $this->mall_id;
                $log->user_id = $uid;
                $log->integral = $this->integral;
                $log->year = $year;
                if ($log->save()) {
                    $i++;
                    IntegralLogHelper::add($log->user_id, $log->integral, '生日积分');
                }
            }
        }
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '发放完成，人数：' . $i);
    }
}