<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/3/12
 * Time: 10:55
 * Note:
 */

namespace app\plugins\integral\forms\mall;

use app\core\ApiCode;
use app\helpers\ResponseHelper;
use app\models\BaseModel;

use app\models\User;
use app\plugins\integral\models\IntegralBirthdaySendLog;

class IntegralBirthdaySendLogListForm extends BaseModel
{
    public $page;
    public $limit;

    public function rules()
    {
        return [
            [['page', 'limit'], 'integer'],
        ]; // TODO: Change the autogenerated stub
    }


    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        $query = IntegralBirthdaySendLog::find()->alias('l')->leftJoin(['u' => User::tableName()], 'u.id=l.user_id')
            ->select('l.*,u.nickname,u.avatar_url');
        $list = $query->page($pagination, $this->limit, $this->page)->asArray()->all();

        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagination]);

    }
}