<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-22
 * Time: 16:46
 */

namespace app\forms\api\qrcode;


use app\core\ApiCode;
use app\models\BaseModel;
use Endroid\QrCode\QrCode;

class QrcodeForm extends BaseModel
{

    public $path;
    public $params;
    public $type; //0普通二维码  1 小程序码

    public function rules()
    {
        return [
            [['path', 'params'], 'string'],
            [['type'], 'integer']
        ]; // TODO: Change the autogenerated stub
    }

    public function generate()
    {

        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        if ($this->type) {

        }

        $mall = \Yii::$app->mall;
        $user_id = \Yii::$app->user->identity->id;
        $qrCode = new QrCode("{$this->path}&mall_id={$mall->id}&pid={$user_id}");
        $qrCode->setSize(200);
        $qrCode->setMargin(10);
        $baseWebPath = \Yii::$app->basePath . '/web';
        $baseWebUrl = \Yii::$app->request->hostInfo . \Yii::$app->request->baseUrl;
        $saveName = md5($this->params) . '.png';
        $savePath = '/qrcode/' . \Yii::$app->user->identity->id . '/';
        $saveFile = $baseWebPath . $savePath . $saveName;
        if (!is_dir($baseWebPath . $savePath)) {
            if (!make_dir($baseWebPath . $savePath)) {
                throw new \Exception('上传失败，创建文件夹失败`'
                    . $baseWebPath . $savePath
                    . '`，请检查目录写入权限。');
            }
        }
        $qrCode->writeFile($saveFile);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['url' => $baseWebUrl . $savePath . $saveName]);

    }


}