<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/5/28
 * Time: 11:10
 * Note:
 */

namespace app\forms\api\mall;


use app\core\ApiCode;
use app\helpers\ResponseHelper;
use app\models\BaseModel;
use app\models\OutsideLink;

class OutsideLinkForm extends BaseModel
{
    public $id;

    public function rules()
    {
        return [
            [['id'], 'integer'],
        ]; // TODO: Change the autogenerated stub
    }

    public function search()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $link = OutsideLink::getOne($this->id);
        if (!$link) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, '链接不存在');
        }

        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['link' => $link->attributes]);

    }

}