<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-22
 * Time: 12:04
 */

namespace app\forms\api\wechat;


use app\core\ApiCode;
use app\helpers\OptionHelper;
use app\helpers\SerializeHelper;
use app\models\BaseModel;
use yii\helpers\Json;

class WechatForm extends BaseModel
{

    public $url;

    public function rules()
    {
        return [
            [['url'], 'string']

        ]; // TODO: Change the autogenerated stub
    }

    public function getJssdk()
    {
        $app = \Yii::$app->wechat->app;

        $app->jssdk->setUrl($this->url);
        try {
            $jssdk = $app->jssdk->buildConfig(['updateAppMessageShareData', 'updateTimelineShareData', 'chooseWXPay'], $debug = false, $beta = false, $json = true);
            if ($jssdk) {
                $jssdk = Json::decode($jssdk);
            }
        } catch (\Exception $e) {
            $jssdk = [];
        }
        $mall_setting = OptionHelper::get('mall_setting', \Yii::$app->mall->id);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['jssdk' => $jssdk, 'default_share' => ['logo' => $mall_setting['logo'], 'name' => $mall_setting['name'], 'detail' => $mall_setting['detail']]]);
    }

}