<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-12
 * Time: 15:48
 */

namespace app\forms\api\cart;


use app\core\ApiCode;
use app\helpers\SerializeHelper;
use app\models\BaseModel;
use app\models\Cart;

class CartEditForm extends BaseModel
{
    public $edit_data;

    public $is_delete;

    public function rules()
    {
        return [
            [['is_delete'], 'integer'],
            [['edit_data'], 'safe']
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $this->edit_data = SerializeHelper::decode($this->edit_data);
        foreach ($this->edit_data as $row) {
            $cart = Cart::findOne(['user_id' => \Yii::$app->user->identity->id, 'id' => $row['id'], 'is_delete' => 0]);
            if (!$cart) {
                return $this->apiResponse(ApiCode::CODE_FAIL, '商品不存在');
            }
            if (!$this->is_delete) {
                $cart->num = $row['num'];
            } else {
                $cart->is_delete = 1;
            }

            $cart->save();
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '编辑完成');
    }
}