<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-12
 * Time: 16:36
 */

namespace app\forms\api\cart;


use app\core\ApiCode;
use app\models\BaseModel;
use app\models\Cart;

class CartDeleteForm extends BaseModel
{
    public $id;

    public function rules()
    {
        return [
            [['id'], 'required'],
            [['id'], 'integer'],
        ]; // TODO: Change the autogenerated stub
    }

    public function delete()
    {

        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $cart = Cart::findOne(['id' => $this->id, 'is_delete' => 0, 'user_id' => \Yii::$app->user->identity->id]);
        if (!$cart) {
            $this->apiResponse(ApiCode::CODE_FAIL, '商品不存在或已被删除!');
        }

        $cart->is_delete = 1;
        if (!$cart->save()) {
            return $this->responseErrorMsg($cart);
        }


        return $this->apiResponse(ApiCode::CODE_SUCCESS,'删除成功');


    }
}