<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-30
 * Time: 10:30
 */

namespace app\plugins\share\forms\mall;


use app\core\ApiCode;
use app\helpers\OptionHelper;
use app\helpers\SerializeHelper;
use app\models\BaseModel;
use app\plugins\share\models\Share;
use app\plugins\share\models\ShareLevel;

class LevelForm extends BaseModel
{
    public $id;
    public $level;
    public $name;
    public $first_price;
    public $second_price;
    public $third_price;
    public $price_type;
    public $upgrade;

    public function rules()
    {
        return [
            [['level', 'id', 'price_type'], 'integer'],
            [['name'], 'string'],
            [['upgrade'], 'safe'],
            [['first_price', 'second_price', 'third_price'], 'number'],
            [['name'], 'string', 'max' => 45]
        ]; // TODO: Change the autogenerated stub
    }


    public function save()
    {

        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        if (!$this->first_price) {
            $this->first_price = 0;
        }
        if (!$this->second_price) {
            $this->second_price = 0;
        }
        if (!$this->third_price) {
            $this->third_price = 0;
        }

        $level = ShareLevel::findOne(['id' => $this->id, 'mall_id' => \Yii::$app->mall->id, 'is_delete' => 0]);
        if ($this->id) {
            if (!$level) {
                return $this->apiResponse(ApiCode::CODE_FAIL, '该等级不存在,或已被删除！');
            }
            if ($level->level != $this->level) {
                //这里要判断有没有分销商已经是这个等级了 如果是这个等级那么不可以替换

                $exist = Share::find()->where(['is_delete' => 0, 'level' => $level->level, 'mall_id' => \Yii::$app->mall->id]);
                if ($exist) {
                    return $this->apiResponse(ApiCode::CODE_FAIL, '该等级存在分销商不可更改');
                }
            }
        }
        if (!$level) {
            $level = new ShareLevel();
            $level->mall_id = \Yii::$app->mall->id;
        }
        $level->attributes = $this->attributes;
        if (!$level->save()) {
            return $this->responseErrorMsg($level);
        }
        $this->upgrade = SerializeHelper::encode($this->upgrade);
        $this->id = $level->id;
        OptionHelper::set('share_level_' . $level->id, $this->attributes, \Yii::$app->mall->id);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }

    public function search()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        $level = OptionHelper::get('share_level_' . $this->id, \Yii::$app->mall->id);
        if ($level) {
            if ($level['upgrade']) {
                $level['upgrade'] = SerializeHelper::decode($level['upgrade']);
            }
            return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['level' => $level]);
        }
        $level = ShareLevel::findOne(['mall_id' => \Yii::$app->mall->id, 'id' => $this->id, 'is_delete' => 0]);
        if (!$level) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '等级不存在！');
        }
        $this->id = $level->id;
        OptionHelper::set('share_level_' . $level->id, $level->attributes, \Yii::$app->mall->id);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['level' => $level]);
    }

    public function delete()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $level = ShareLevel::findOne(['mall_id' => \Yii::$app->mall->id, 'id' => $this->id, 'is_delete' => 0]);
        if (!$level) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '等级不存在！');
        }
        //判断下面还有没有用户是这个等级的

        $level->is_delete = 1;
        if (!$level->save()) {
            return $this->responseErrorMsg($level);
        }
        OptionHelper::remove('share_level_' . $level->id, \Yii::$app->mall->id);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '删除成功');
    }

    public function getDefault()
    {
        $list = [[
            "level" => 0,
            'name' => '默认等级',
            'is_use' => 0,
        ]];
        for ($i = 1; $i < 30; $i++) {
            $item = [
                "level" => $i,
                'name' => $i . '级',
                'is_use' => 0,
            ];
            $list[] = $item;
        }
        $use_levels = ShareLevel::find()->where(['is_delete' => 0, 'mall_id' => \Yii::$app->mall->id])->select('level')->column();
        foreach ($list as &$item) {
            if (in_array($item['level'], $use_levels)) {
                $item['is_use'] = 1;
            }
        }
        unset($item);
        $setting = OptionHelper::get('share_setting', \Yii::$app->mall->id);
        if (!$setting) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '未配置分销');
        }

        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'setting' => $setting]);
    }

}