<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-11-02
 * Time: 16:13
 */

namespace app\plugins\share\forms\mall;


use app\core\ApiCode;
use app\helpers\OptionHelper;
use app\models\BaseModel;
use app\plugins\share\models\Share;
use app\plugins\share\models\ShareApply;
use app\plugins\share\models\ShareLevel;

class ShareApplyStatusForm extends BaseModel
{

    public $id;

    public $status;

    public function rules()
    {
        return [
            [['id', 'status'], 'integer']
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {

        if (!$this->validate()) {
            return $this->responseErrorInfo();

        }
        $apply = ShareApply::findOne(['status' => 0, 'id' => $this->id]);
        if (!$apply) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '申请记录不存在！');
        }
        $apply->status = $this->status;
        if ($apply->status == 1) {
            $share = Share::findOne(['user_id' => $apply->user_id, 'is_delete' => 0]);
            if (!$share) {
                $level = ShareLevel::findOne(['level' => 0, $apply->mall_id]);
                if (!$level) {
                    return $this->apiResponse(ApiCode::CODE_FAIL, '默认等级不存在！');
                }
                $share = new Share();
                $share->user_id = $apply->user_id;
                $share->mall_id = $apply->mall_id;
                $share->level_id = $level->id;
                $share->level = $level->level;
                if (!$share->save()) {
                    return $this->responseErrorMsg($share);
                }
            }
        }
        if (!$apply->save()) {
            return $this->responseErrorMsg($apply->getErrors());
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '处理成功');
    }

}