<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-30
 * Time: 23:28
 */

namespace app\plugins\share\forms\mall;


use app\core\ApiCode;
use app\models\BaseModel;
use app\plugins\share\models\Share;
use app\plugins\share\models\ShareLevel;

class ShareForm extends BaseModel
{
    public $user_id;
    public $level;
    public $is_auto;


    public function rules()
    {
        return [
            [['user_id', 'level', 'is_auto'], 'integer'],
        ]; // TODO: Change the autogenerated stub
    }

    public function levelChange()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $share = Share::findOne(['is_delete' => 0, 'mall_id' => \Yii::$app->mall->id, 'user_id' => $this->user_id]);
        if (!$share) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '用户不存在！');
        }
        $level = ShareLevel::findOne(['level' => $this->level, 'mall_id' => \Yii::$app->mall->id, 'is_delete' => 0]);
        if (!$level) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '等级不存在！');
        }
        if ($share->level != $this->level) {
            $share->level = $this->level;
            $share->level_id = $level->id;
            $share->is_manual = 1;
            $share->level_at = time();
            if (!$share->save()) {
                return $this->responseErrorMsg($share);
            }
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }


    public function autoUpgrade()
    {

        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $share = Share::findOne(['is_delete' => 0, 'mall_id' => \Yii::$app->mall->id, 'user_id' => $this->user_id]);
        if (!$share) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '用户不存在！');
        }
        $share->is_auto = $this->is_auto;
        if (!$share->save()) {
            return $this->responseErrorMsg($share);
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }

    public function add()
    {

        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $share = Share::findOne(['is_delete' => 0, 'mall_id' => \Yii::$app->mall->id, 'user_id' => $this->user_id]);
        if ($share) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '该用户已经是分销商！');
        }
        $share = new Share();
        $share->mall_id = \Yii::$app->mall->id;
        $share->user_id = $this->user_id;
        $share->level = 0;
        $share->is_auto = $this->is_auto;
        if (!$share->save()) {
            return $this->responseErrorMsg($share);
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }

}