<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-30
 * Time: 23:03
 */

namespace app\plugins\share\forms\mall;


use app\core\ApiCode;
use app\helpers\IconHelper;
use app\helpers\OptionHelper;
use app\models\BaseModel;
use app\models\Level;
use app\models\User;
use app\models\UserParent;
use app\plugins\share\models\Share;
use app\plugins\share\models\ShareLevel;
use app\plugins\share\models\ShareOrder;

class ShareInfoForm extends BaseModel
{
    public $user_id;


    public function rules()
    {
        return [
            [['user_id'], 'required'],
            [['user_id'], 'integer'],
        ]; // TODO: Change the autogenerated stub
    }


    public function search()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $info = [];
        $user = User::findOne(['is_delete' => 0, 'id' => $this->user_id, 'mall_id' => \Yii::$app->mall->id]);
        if (!$user) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '用户不存在!');
        }
        $share = Share::findOne(['is_delete' => 0, 'user_id' => $this->user_id]);
        if (!$share) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '该用户不是分销商');
        }
        $mall = OptionHelper::get('mall_setting', \Yii::$app->mall->id);
        $info['nickname'] = $user->nickname;
        $info['avatar_url'] = $user->avatar_url;
        $info['money'] = $user->money;
        $info['integral'] = $user->integral;
        $info['mobile'] = $user->mobile;
        $info['remarks'] = $user->remarks;
        $info['created_at'] = date('Y-m-d H:i:s', $user->created_at);
        $info['updated_at'] = date('Y-m-d H:i:s', $user->updated_at);
        $info['login_ip'] = $user->login_ip;
        $info['id'] = $user->id;
        if ($user->platform == User::PLATFORM_WECHAT || $user->platform == User::PLATFORM_WXAPP) {
            $info['platform_logo'] = IconHelper::wechat();
        }
        if ($user->platform == User::PLATFORM_MPWX) {
            $info['platform_logo'] = IconHelper::mpwx();
        }
        $level = Level::findOne(['mall_id' => $user->mall_id, 'level' => $user->level, 'is_delete' => 0]);
        $info['level_name'] = "默认等级";
        if ($level) {
            $info['level_name'] = $level->name;
        }
        $level_list = ShareLevel::find()->where(['mall_id' => \Yii::$app->mall->id, 'is_delete' => 0,])->asArray()->all();

        $parent = $user->getParent();
        if ($parent) {
            $info['parent_name'] = $parent->nickname;
            $info['parent_id'] = $parent->id;
            $info['parent_avatar'] = $parent->avatar_url;
        } else {
            $info['parent_name'] = '平台';
            $info['parent_id'] = 0;
            $info['parent_avatar'] = $mall['logo'];
        }
        $shareLevel = ShareLevel::findOne(['level' => $share->level, 'mall_id' => $share->mall_id, 'is_delete' => 0]);
        if ($shareLevel) {
            $info['share_level_name'] = $shareLevel->name;
            $info['share_level'] = $shareLevel->level;
        } else {
            $info['share_level_name'] = '默认等级';
            $info['share_level'] = '0';
        }
        $info['price'] = $user->price;
        $info['share_at'] = date('Y-m-d H:i:s', $share->created_at);
        $info['updated_at'] = date('Y-m-d H:i:s', $share->updated_at);
        $info['is_auto'] = $share->is_auto;
        $info['child_all'] = UserParent::find()->where(['parent_id' => $user->id, 'is_delete' => 0])->count();
        $info['child_first'] = UserParent::find()->where(['parent_id' => $user->id, 'is_delete' => 0, 'level' => 1])->count();
        $info['child_second'] = UserParent::find()->where(['parent_id' => $user->id, 'is_delete' => 0, 'level' => 2])->count();
        $info['child_third'] = UserParent::find()->where(['parent_id' => $user->id, 'is_delete' => 0, 'level' => 3])->count();
        $info['child_share_all'] = UserParent::find()->alias('u')->leftJoin(['s' => Share::tableName()], 's.user_id=u.user_id')->where(['u.parent_id' => $user->id, 'u.is_delete' => 0, 's.is_delete' => 0])->count();
        $info['child_share_first'] = UserParent::find()->alias('u')->leftJoin(['s' => Share::tableName()], 's.user_id=u.user_id')->where(['u.parent_id' => $user->id, 'u.is_delete' => 0, 's.is_delete' => 0, 'u.level' => 1])->count();
        $info['child_share_second'] = UserParent::find()->alias('u')->leftJoin(['s' => Share::tableName()], 's.user_id=u.user_id')->where(['u.parent_id' => $user->id, 'u.is_delete' => 0, 's.is_delete' => 0, 'u.level' => 2])->count();
        $info['child_share_third'] = UserParent::find()->alias('u')->leftJoin(['s' => Share::tableName()], 's.user_id=u.user_id')->where(['u.parent_id' => $user->id, 'u.is_delete' => 0, 's.is_delete' => 0, 'u.level' => 3])->count();
        $info['share_order'] = ShareOrder::find()->where(['is_delete' => 0, 'mall_id' => $share->mall_id])->andWhere(['or', ['parent_id_1' => $share->user_id], ['parent_id_2' => $share->user_id], ['parent_id_2' => $share->user_id]])->count();
        $info['total_share_price'] = $share->total_price;


        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['user' => $info, 'level_list' => $level_list]);
    }

}