<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-11-02
 * Time: 11:01
 */

namespace app\plugins\share\forms\mall;


use app\core\ApiCode;
use app\models\BaseModel;
use app\models\CommonOrder;
use app\models\CommonOrderDetail;
use app\models\Goods;
use app\models\User;
use app\models\UserParent;
use app\plugins\share\models\ShareOrder;
use app\plugins\share\models\SharePriceLog;

class ShareOrderListForm extends BaseModel
{

    public $page;
    public $limit;
    public $keyword;
    public $user_id;

    public function rules()
    {
        return [

            [['page', 'limit', 'user_id'], 'integer'],
            [['keyword'], 'string'],
            [['limit'], 'default', 'value' => 10]

        ]; // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        $query = ShareOrder::find()
            ->alias('so')
            ->leftJoin(['u' => User::tableName()], 'u.id=so.user_id')
            ->leftJoin(['co' => CommonOrder::tableName()], 'so.common_order_id=co.id')
            ->andWhere(['so.is_delete' => 0, 'u.is_delete' => 0]);
        if ($this->user_id) {
            $child_ids = UserParent::find()->where(['is_delete' => 0, 'parent_id' => $this->user_id])->select('user_id')->column();
            $query->andWhere(['user_id' => $child_ids]);
        }
        $list = $query->page($pagination, $this->limit, $this->page)
            ->select('u.nickname,u.avatar_url,so.*,co.order_no')
            ->orderBy('so.updated_at desc')
            ->asArray()->all();
        foreach ($list as &$item) {

            $item['created_at'] = date('Y-m-d H:i:s', $item['created_at']);
            $item['parent_1'] = User::getBaseInfo($item['parent_id_1']);
            if ($item['parent_id_2']) {
                $item['parent_2'] = User::getBaseInfo($item['parent_id_2']);
            }
            if ($item['parent_id_3']) {
                $item['parent_3'] = User::getBaseInfo($item['parent_id_3']);
            }
            $log_list = SharePriceLog::find()->alias('l')
                ->leftJoin(['u' => User::tableName()], 'u.id=l.user_id')
                ->leftJoin(['c' => CommonOrderDetail::tableName()], 'c.id=l.common_order_detail_id')
                ->where(['l.share_order_id' => $item['id']])
                ->select('l.*,u.nickname,u.avatar_url,c.num,c.price as goods_price')
                ->asArray()
                ->all();

            foreach ($log_list as &$log) {
                if ($log['goods_type'] == 0) {
                    $goods = Goods::getBaseInfo($log['goods_id']);
                    $log['goods'] = $goods;
                }
                if ($log['user_id'] == $item['parent_id_1']) {
                    $log['level'] = 1;
                }
                if ($log['user_id'] == $item['parent_id_2']) {
                    $log['level'] = 2;
                }
                if ($log['user_id'] == $item['parent_id_3']) {

                    $log['level'] = 3;
                }
            }
            unset($log);

            $item['list'] = $log_list;

        }
        unset($item);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagination]);
    }


}