<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-30
 * Time: 17:01
 */

namespace app\plugins\share\forms\mall;


use app\core\ApiCode;
use app\helpers\IconHelper;
use app\models\BaseModel;
use app\models\CommonOrder;
use app\models\User;
use app\plugins\share\models\Share;
use app\plugins\share\models\ShareLevel;

class ShareListForm extends BaseModel
{

    public $page;
    public $limit;
    public $keyword;

    public function rules()
    {
        return [

            [['limit', 'page'], 'integer'],
            [['limit'], 'default', 'value' => 10],
            [['keyword'], 'string']

        ]; // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $query = Share::find()->alias('s')->leftJoin(['u' => User::tableName()], 'u.id=s.user_id')
            ->andWhere(['s.is_delete' => 0, 's.mall_id' => \Yii::$app->mall->id]);
        if ($this->keyword) {
            $query->andWhere(['like', 'u.nickname', $this->keyword]);
        }
        $list = $query->page($pagination, $this->limit, $this->page)->select('u.nickname,u.avatar_url,u.price,u.platform,u.mobile,u.parent_id,u.integral,u.money,s.*')->asArray()->all();

        foreach ($list as &$item) {
            $item['created_at'] = date('Y-m-d H:i:s', $item['created_at']);
            $level = ShareLevel::findOne(['is_delete' => 0, 'mall_id' => \Yii::$app->mall->id, 'level' => $item['level']]);
            if (!$level) {
                $item['level'] = '默认等级';
            } else {
                $item['level'] = $level->name;
            }

            $item['total_order_price'] = CommonOrder::find()->where(['user_id' => $item['user_id'], 'is_delete' => 0, 'status' => 1])->sum('pay_price');
            $item['order_num'] = CommonOrder::find()->where(['user_id' => $item['user_id'], 'is_delete' => 0, 'status' => 1])->count();
            if ($item['platform'] == User::PLATFORM_WECHAT) {
                $item['platform_logo'] = IconHelper::wechat();
            }
            if ($item['platform'] == User::PLATFORM_MPWX) {
                $item['platform_logo'] = IconHelper::mpwx();
            }
            if ($item['platform'] == User::PLATFORM_WXAPP) {
                $item['platform_logo'] = IconHelper::wxapp();
            }
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagination]);
    }
}