<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-11-04
 * Time: 21:29
 */

namespace app\plugins\share\controllers\api;


use app\controllers\api\filters\LoginFilter;
use app\plugins\ApiController;

use app\plugins\share\forms\api\ShareInfoForm;
use app\plugins\share\forms\api\SharePriceLogListForm;

class ShareController extends ApiController
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(),
            ['login' => LoginFilter::class]
        ); // TODO: Change the autogenerated stub
    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2020-11-04
     * @Time: 21:30
     * @Note:分销商信息
     */
    public function actionInfo()
    {


        $form = new ShareInfoForm();
        $form->attributes = $this->request->get();
        return $this->asJson($form->getInfo());

    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2020-11-04
     * @Time: 22:15
     * @Note:佣金记录
     */
    public function actionPriceLog()
    {
        $form = new SharePriceLogListForm();
        $form->attributes = $this->request->get();
        return $this->asJson($form->getList());
    }

}