<?php

namespace app\models;

use app\helpers\DateHelper;
use Yii;

/**
 * This is the model class for table "{{%admin_action_log}}".
 *
 * @property int $id
 * @property int $mall_id
 * @property int|null $admin_id
 * @property string|null $model
 * @property int $model_id
 * @property string|null $before_update
 * @property string|null $after_update
 * @property string|null $remarks
 * @property int|null $updated_at
 * @property int|null $created_at
 * @property int|null $deleted_at
 * @property int $is_delete
 * @property string|null $log_at 更新时间
 */
class AdminActionLog extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%admin_action_log}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id', 'admin_id', 'model_id', 'updated_at', 'created_at', 'deleted_at', 'is_delete'], 'integer'],
            [['log_at'], 'safe'],
            [['model'], 'string', 'max' => 128],
            [['before_update', 'after_update'], 'string'],
            [['remarks'], 'string', 'max' => 255],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'Mall ID',
            'admin_id' => 'Admin ID',
            'model' => 'Model',
            'model_id' => 'Model ID',
            'before_update' => 'Before Update',
            'after_update' => 'After Update',
            'remarks' => 'Remarks',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
            'deleted_at' => 'Deleted At',
            'is_delete' => 'Is Delete',
            'log_at' => 'Log At',
        ];
    }

    public function beforeSave($insert)
    {
        $this->log_at = DateHelper::format(time());
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
