<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%api}}".
 *
 * @property int $id
 * @property string|null $path 接口路径
 * @property string|null $api_group 分组
 * @property string|null $method 请求方法
 * @property string|null $description 简介
 * @property int|null $updated_at 更新时间
 * @property int $deleted_at 删除时间
 * @property int|null $created_at 创建时间
 * @property int|null $is_delete 是否删除
 * @property string $created_time 创建时间
 * @property string|null $uniqueid 唯一ID
 */
class Api extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%api}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['updated_at', 'deleted_at', 'created_at', 'is_delete'], 'integer'],
            [['created_time'], 'safe'],
            [['uniqueid'],'string','max'=>64],
            [['path', 'api_group', 'description'], 'string', 'max' => 255],
            [['method'], 'string', 'max' => 10],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'path' => '接口路径',
            'api_group' => '分组',
            'method' => '请求方法',
            'description' => '简介',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
            'created_at' => '创建时间',
            'is_delete' => '是否删除',
            'created_time' => '创建时间',
        ];
    }
    public function beforeSave($insert)
    {
        if($insert){
            $this->uniqueid=uniqid();
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
