<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-09
 * Time: 17:58
 */

namespace app\models;

use app\core\ApiCode;

class BaseModel extends \yii\base\Model
{
    public $mall_id;
    public $page;
    public $limit = 10;
    public $pagination;

    public function rules()
    {
        return [
            [['page', 'limit'], 'integer']
        ]; // TODO: Change the autogenerated stub
    }

    public function init()
    {
        $this->mall_id = \Yii::$app->mall->id;
        parent::init(); // TODO: Change the autogenerated stub
    }

    /**
     * 返回错误数据数组
     * @param array $model
     * @return array
     */
    public function responseErrorInfo($model = [])
    {
        if (!$model) {
            $model = $this;
        }
        $msg = isset($model->errors) ? current($model->errors)[0] : '数据异常！';
        return [
            'code' => ApiCode::CODE_FAIL,
            'msg' => $msg
        ];
    }

    /**
     * 返回错误数据文本信息
     * @param array $model
     * @return array
     */
    public function responseErrorMsg($model = null)
    {
        if (!$model) {
            $model = $this;
        }
        $msg = isset($model->errors) ? current($model->errors)[0] : '数据异常！';
        return [
            'code' => ApiCode::CODE_FAIL,
            'msg' => $msg
        ];

    }


    public function apiResponse($code = 0, $msg = '', $data = [])
    {
        if (!$msg) {
            $msg = '数据请求成功';
        }
        return ['code' => $code, 'msg' => $msg, 'data' => $data];
    }


    /**
     * 获取分页数据
     * @param $pagination
     * @return array
     */
    public function getPaginationInfo($pagination)
    {
        $pageData = [];
        $pageData["total_count"] = $pagination->total_count;
        $pageData["page_count"] = $pagination->page_count;
        $pageData["pageSize"] = $pagination->pageSize;
        $pageData["current_page"] = $pagination->current_page;
        return $pageData;
    }
}
