<?php

namespace app\models;

use app\events\CommonOrderDetailEvent;
use app\helpers\JobHelper;
use app\jobs\goods\GoodsSalesJob;
use Yii;

/**
 * This is the model class for table "{{%common_order_detail}}".
 *
 * @property int $id
 * @property int $mall_id
 * @property int $common_order_id
 * @property int $user_id
 * @property float $price
 * @property int $goods_id
 * @property int|null $deleted_at
 * @property int|null $updated_at
 * @property int|null $created_at
 * @property int $is_delete
 * @property int $is_price
 * @property int|null $price_time
 * @property string|null $common_order_no
 * @property string|null $attr
 * @property int $num
 * @property int $status 0 正常 1 有效  2 无效
 * @property float|null $coupon_cut_price 优惠券减掉的金额
 * @property int|null $user_coupon_id 用户优惠券ID
 * @property float|null $integral_cut_price 积分减掉的金额
 * @property int|null $use_integral 使用了多少积分
 * @property float|null $pay_price 实际支付金额
 * @property float|null $total_price 总计价格
 * @property int $is_send 是否发货
 * @property int $express_log_id 发货记录
 * @property Goods $goods
 */
class CommonOrderDetail extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%common_order_detail}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id', 'common_order_id', 'user_id', 'price', 'goods_id'], 'required'],
            [['mall_id', 'express_log_id', 'is_send', 'common_order_id', 'user_id', 'goods_id', 'deleted_at', 'updated_at', 'created_at', 'is_delete', 'is_price', 'price_time', 'num', 'status', 'user_coupon_id', 'use_integral'], 'integer'],
            [['price', 'coupon_cut_price', 'integral_cut_price', 'pay_price', 'total_price'], 'number'],
            [['common_order_no'], 'string', 'max' => 45],
            [['attr'], 'string', 'max' => 512],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'Mall ID',
            'common_order_id' => 'Common Order ID',
            'user_id' => 'User ID',
            'price' => 'Price',
            'goods_id' => 'Goods ID',
            'deleted_at' => 'Deleted At',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
            'is_delete' => 'Is Delete',
            'is_price' => 'Is Price',
            'price_time' => 'Price Time',
            'common_order_no' => 'Common Order No',
            'attr' => 'Attr',
            'num' => 'Num',
            'status' => '0 正常 1 有效  2 无效',
            'coupon_cut_price' => '优惠券减掉的金额',
            'user_coupon_id' => '用户优惠券ID',
            'integral_cut_price' => '积分减掉的金额',
            'use_integral' => '使用了多少积分',
            'pay_price' => '实际支付金额',
            'total_price' => '总计价格',
            'express_log_id' => '发货记录',
            'is_send' => '是否发货'
        ];
    }

    public function getGoods()
    {
        return $this->hasOne(Goods::className(), ['id' => 'goods_id']);
    }

    public function afterSave($insert, $changedAttributes)
    {
        // TODO: Change the autogenerated stub
        parent::afterSave($insert, $changedAttributes);
        if ($insert) {
            $event = new CommonOrderDetailEvent();
            $event->id = $this->id;
            Yii::$app->trigger(CommonOrderDetailEvent::INSERT, $event);
            JobHelper::push(new GoodsSalesJob(['common_order_detail_id' => $this->id, 'status' => 1]), 3);
        }
    }
}
