<?php

namespace app\models;

use app\helpers\CacheHelper;
use app\helpers\JobHelper;
use app\jobs\CouponExpireJob;
use app\jobs\market\UserCouponExpireJob;
use Yii;

/**
 * This is the model class for table "{{%coupon}}".
 *
 * @property int $id
 * @property int $mall_id
 * @property string $name
 * @property int $is_limit_total 总数限制
 * @property float $discount 折扣多少
 * @property float $price 金额满
 * @property int $time_type 时间类型 0 领取后几天  1日期范围
 * @property int $total
 * @property int $day
 * @property int|null $start_at
 * @property int|null $end_at
 * @property int $is_join 是否加入领券中心
 * @property int $user_total 每个用户最多领取
 * @property int $is_goods_limit 是否限制商品使用
 * @property int $type 0满减券  1 折扣
 * @property int $user_total_limit 用户领取限制
 * @property int $is_delete
 * @property int|null $created_at
 * @property int|null $deleted_at
 * @property int|null $updated_at
 * @property int $mch_id
 * @property integer $is_expire
 */
class Coupon extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%coupon}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id', 'name', 'total', 'day', 'is_goods_limit', 'type'], 'required'],
            [['mall_id', 'is_expire', 'is_limit_total', 'time_type', 'total', 'day', 'start_at', 'end_at', 'is_join', 'user_total', 'is_goods_limit', 'type', 'user_total_limit', 'is_delete', 'created_at', 'deleted_at', 'updated_at', 'mch_id'], 'integer'],
            [['discount', 'price'], 'number'],
            [['name'], 'string', 'max' => 45],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'Mall ID',
            'name' => 'Name',
            'is_limit_total' => '总数限制',
            'discount' => '折扣多少',
            'price' => '金额满',
            'time_type' => '时间类型 0 领取后几天  1日期范围',
            'total' => 'Total',
            'day' => 'Day',
            'start_at' => 'Start At',
            'end_at' => 'End At',
            'is_join' => '是否加入领券中心',
            'user_total' => '每个用户最多领取',
            'is_goods_limit' => '是否限制商品使用',
            'type' => '0满减券  1 折扣',
            'user_total_limit' => '用户领取限制',
            'is_delete' => 'Is Delete',
            'created_at' => 'Created At',
            'deleted_at' => 'Deleted At',
            'updated_at' => 'Updated At',
            'mch_id' => '商户ID'

        ];
    }

    public function beforeSave($insert)
    {
        if ($this->time_type == 1) {
            if ($this->end_at <= time()) {
                $this->is_expire = 1;
            }
        }
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {
            if ($this->time_type == 1) {
                if ($this->end_at > time()) {
                    JobHelper::push(new CouponExpireJob(['coupon_id' => $this->id]), $this->end_at - time());
                }
            }
        } else {
            if (isset($changedAttributes['time_type']) && $changedAttributes['time_type'] == 1) {
                if ($this->end_at > time()) {
                    JobHelper::push(new CouponExpireJob(['coupon_id' => $this->id]), $this->end_at - time());
                }
            }
        }

        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }


    public static function decTotal($id, $num = 0)
    {
        Yii::$app->redis->decrby(CacheHelper::getKeyName('total_coupon_' . $id), $num);
        $total = self::getTotal($id);
        $total = $total ?? 0;
        self::updateAll(['total' => $total], ['id' => $id]);
    }

    public static function setTotal($id, $num = 0)
    {
        Yii::$app->redis->set(CacheHelper::getKeyName('total_coupon_' . $id), $num);
    }

    public static function incrTotal($id, $num = 0)
    {
        Yii::$app->redis->incrby(CacheHelper::getKeyName('total_coupon_' . $id), $num);
        $total = self::getTotal($id);
        $total = $total ?? 0;
        self::updateAll(['total' => $total], ['id' => $id]);
    }


    public static function getTotal($id)
    {
        return Yii::$app->redis->get(CacheHelper::getKeyName('total_coupon_' . $id));
    }


    public static function delCoupon($id)
    {
        Yii::$app->redis->del(CacheHelper::getKeyName('total_coupon_' . $id));
    }
}
