<?php

namespace app\models;

use app\helpers\JobHelper;
use Yii;

/**
 * This is the model class for table "{{%goods_up_down_job}}".
 *
 * @property int $id
 * @property int $mall_id
 * @property int|null $goods_id 商品ID
 * @property int $action_at 执行时间
 * @property string $action_time 执行时间
 * @property int $status 1下架  2 上架
 * @property int $is_done 是否执行
 * @property int|null $updated_at 更新时间
 * @property int $deleted_at 删除时间
 * @property int|null $created_at 创建时间
 * @property int|null $is_delete 是否删除
 * @property string $created_time 创建时间
 */
class GoodsUpDownJob extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%goods_up_down_job}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id'], 'required'],
            [['mall_id', 'goods_id', 'action_at', 'status', 'is_done', 'updated_at', 'deleted_at', 'created_at', 'is_delete'], 'integer'],
            [['created_time'], 'safe'],
            [['action_time'], 'string', 'max' => 45],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'Mall ID',
            'goods_id' => '商品ID',
            'action_at' => '执行时间',
            'action_time' => '执行时间',
            'status' => '1下架  2 上架',
            'is_done' => '是否执行',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
            'created_at' => '创建时间',
            'is_delete' => '是否删除',
            'created_time' => '创建时间',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        JobHelper::push(new \app\jobs\goods\GoodsUpDownJob(['job_id' => $this->id]), $this->action_at - time());
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
