<?php

namespace app\models;

use Yii;

/**
 * This is the model class for table "{{%goods_attr}}".
 *
 * @property int $id
 * @property int $mall_id
 * @property int $goods_id
 * @property int $is_delete
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $deleted_at
 * @property int $stock
 * @property float $price
 * @property string|null $pic_url
 * @property string|null $no
 * @property int|null $weight
 * @property string|null $attr_list
 */
class GoodsAttr extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%goods_attr}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id', 'goods_id'], 'required'],
            [['mall_id', 'goods_id', 'is_delete', 'created_at', 'updated_at', 'deleted_at', 'stock', 'weight'], 'integer'],
            [['price'], 'number'],
            [['pic_url'], 'string', 'max' => 255],
            [['no'], 'string', 'max' => 45],
            [['attr_list'], 'string', 'max' => 2046],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'Mall ID',
            'goods_id' => 'Goods ID',
            'is_delete' => 'Is Delete',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'stock' => 'Stock',
            'price' => 'Price',
            'pic_url' => 'Pic Url',
            'no' => 'No',
            'weight' => 'Weight',
            'attr_list' => 'Attr List',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {
        Goods::setStock($this->goods_id, $this->stock, $this->id);
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
