<?php

namespace app\models;

use app\events\UnionOrderEvent;
use Yii;
use yii\base\BaseObject;

/**
 * This is the model class for table "{{%union_order}}".
 *
 * @property int $id
 * @property int $mall_id
 * @property float $pay_price
 * @property int $user_id
 * @property string|null $union_no
 * @property int $is_pay
 * @property int|null $created_at
 * @property int|null $updated_at
 * @property int|null $deleted_at
 * @property int $is_delete
 * @property int $pay_type
 * @property int $is_cancel
 */
class UnionOrder extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%union_order}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id', 'user_id'], 'required'],
            [['mall_id', 'user_id', 'is_pay', 'created_at', 'updated_at', 'deleted_at', 'is_delete', 'pay_type', 'is_cancel'], 'integer'],
            [['pay_price'], 'number'],
            [['union_no'], 'string', 'max' => 45],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'Mall ID',
            'pay_price' => 'Pay Pirce',
            'user_id' => 'User ID',
            'union_no' => 'Union No',
            'is_pay' => 'Is Pay',
            'created_at' => 'Created At',
            'updated_at' => 'Updated At',
            'deleted_at' => 'Deleted At',
            'is_delete' => 'Is Delete',
            'pay_type' => 'pay_type',
            'is_cancel' => '是否取消'
        ];
    }

    public static function generateOrderNo($user_id)
    {
        while (true) {
            $no = 'U' . date('YmdHis', time()) . time() . $user_id;
            $is_exist = self::find()->where(['union_no' => $no])->exists();
            if (!$is_exist) {
                return $no;
            }
        }
    }

    public function afterSave($insert, $changedAttributes)
    {
        if (!$insert) {
            if (isset($changedAttributes['is_pay'])) {
                $event = new UnionOrderEvent();
                $event->union_order_id = $this->id;
                Yii::$app->trigger(UnionOrderEvent::UNION_ORDER_PAY, $event);
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }

}
