<?php

namespace app\models;

use app\helpers\JobHelper;
use app\jobs\market\UserCouponExpireJob;
use Yii;

/**
 * This is the model class for table "{{%user_coupon}}".
 *
 * @property int $id
 * @property int $mall_id
 * @property int $user_id
 * @property float|null $price
 * @property float|null $discount
 * @property int $type 0 满减  1折扣
 * @property int $is_goods_limit
 * @property int $coupon_id
 * @property int|null $start_at
 * @property int|null $end_at
 * @property int $status 1使用  2 过期
 * @property int|null $updated_at
 * @property int|null $created_at
 * @property int|null $deleted_at
 * @property int $is_delete
 * @property Coupon $coupon
 * @property int $mch_id
 * @property string $code 优惠券码
 * @property string $remarks
 */
class UserCoupon extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user_coupon}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id', 'user_id', 'coupon_id'], 'required'],
            [['code','remarks'], 'string'],
            [['mall_id', 'mch_id', 'user_id', 'type', 'is_goods_limit', 'coupon_id', 'start_at', 'end_at', 'status', 'updated_at', 'created_at', 'deleted_at', 'is_delete'], 'integer'],
            [['price', 'discount'], 'number'],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'Mall ID',
            'user_id' => 'User ID',
            'price' => 'Price',
            'discount' => 'Discount',
            'type' => '0 满减  1折扣',
            'is_goods_limit' => 'Is Goods Limit',
            'coupon_id' => 'Coupon ID',
            'start_at' => 'Start At',
            'end_at' => 'End At',
            'status' => '1使用  2 过期',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
            'deleted_at' => 'Deleted At',
            'is_delete' => 'Is Delete',
            'mch_id' => '商户ID',
            'remarks'=>'remarks'
        ];
    }

    public function getCoupon()
    {
        return $this->hasOne(Coupon::class, ['id' => $this->coupon_id]);
    }

    public function beforeSave($insert)
    {
        if ($this->end_at <= time()) {
            $this->status = 2;
        }
        $count = UserCoupon::find()->andWhere(['user_id' => $this->user_id])->count();
        $count = $count ?? 0;
        $count++;
        $this->code = 'C' . date('YmdHis', time()) . $this->user_id . $count;
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    public function afterSave($insert, $changedAttributes)
    {
        if ($insert) {
            if ($this->end_at > time()) {

                JobHelper::push(new UserCouponExpireJob(['user_coupon_id' => $this->id]),$this->end_at - time());
            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
