<?php

namespace app\models;

use app\helpers\DateHelper;
use Yii;

/**
 * This is the model class for table "{{%user_upgrade_log}}".
 *
 * @property int $id
 * @property int $mall_id
 * @property int $user_id
 * @property int $before_level_id
 * @property int $after_level_id
 * @property int $reason_by 0 购物满   1购买商品 2直推会员
 * @property string $marks
 * @property int|null $updated_at
 * @property int|null $is_delete
 * @property int $deleted_at
 * @property int|null $created_at
 * @property string|null $time_at
 * @property string $created_time
 */
class UserUpgradeLog extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%user_upgrade_log}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id', 'user_id', 'reason_by'], 'required'],
            [['mall_id', 'user_id', 'before_level_id', 'after_level_id', 'reason_by', 'updated_at', 'is_delete', 'deleted_at', 'created_at'], 'integer'],
            [['created_time'], 'safe'],
            [['marks', 'time_at'], 'string', 'max' => 45],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'Mall ID',
            'user_id' => 'User ID',
            'before_level_id' => 'Before Level ID',
            'after_level_id' => 'After Level ID',
            'reason_by' => '0 购物满   1购买商品 2直推会员',
            'marks' => 'Marks',
            'updated_at' => 'Updated At',
            'is_delete' => 'Is Delete',
            'deleted_at' => 'Deleted At',
            'created_at' => 'Created At',
            'time_at' => 'Time At',
            'created_time' => 'Created Time',
        ];
    }
    public function beforeSave($insert)
    {
        $this->time_at=DateHelper::format(time());

        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }
}
