<?php

namespace app\models;

use app\events\WechatOrderEvent;
use Yii;

/**
 * This is the model class for table "{{%wechat_order}}".
 *
 * @property int $id
 * @property int|null $mall_id mall_id
 * @property string|null $order_no 订单号
 * @property float|null $pay_price 支付金额
 * @property string|null $pay_type 支付方式 wehcat join
 * @property int $is_delete 是否删除
 * @property int|null $created_at 创建时间戳
 * @property int|null $updated_at 更新时间
 * @property int|null $deleted_at 删除时间
 * @property string $created_time 创建时间
 * @property string|null $updated_time 更新时间
 * @property string|null $deleted_time 删除时间
 * @property string $class 订单类
 * @property integer $is_pay 是否支付
 * @property string $pay_time 支付时间
 * @property string $transaction_id 交易ID
 * @property string $platform
 */
class WechatOrder extends BaseActiveRecord
{
    const PAY_JOINPAY = 'joinpay';
    const PAY_WECHAT = 'wechat';
    const EVENT_PAY = 'event_pay';

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return '{{%wechat_order}}';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id', 'is_delete', 'created_at', 'updated_at', 'deleted_at', 'is_pay'], 'integer'],
            [['pay_price'], 'number'],
            [['class'], 'string', 'max' => 255],
            [['transaction_id'], 'string', 'max' => 64],
            [['created_time', 'updated_time', 'deleted_time', 'pay_time'], 'safe'],
            [['order_no', 'pay_type', 'platform'], 'string', 'max' => 45],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'mall_id' => 'mall_id',
            'order_no' => '订单号',
            'pay_price' => '支付金额',
            'pay_type' => '支付方式 wehcat join',
            'is_delete' => '是否删除',
            'created_at' => '创建时间戳',
            'updated_at' => '更新时间',
            'deleted_at' => '删除时间',
            'created_time' => '创建时间',
            'updated_time' => '更新时间',
            'deleted_time' => '删除时间',
        ];
    }

    public function afterSave($insert, $changedAttributes)
    {

        if (!$insert) {
            if (isset($changedAttributes['is_pay'])) {
                $event = new WechatOrderEvent();
                $event->order_id = $this->id;
                try {
                    Yii::$app->trigger(WechatOrder::EVENT_PAY, $event);
                } catch (\Exception $exception) {
                    Yii::warning('触发--------------------------');
                    Yii::warning($exception->getMessage());
                }

            }
        }
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
