<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-12-31
 * Time: 15:27
 */

namespace app\plugins\article\forms\mall;


use app\core\ApiCode;
use app\helpers\DateHelper;
use app\helpers\ResponseHelper;
use app\models\BaseModel;
use app\plugins\article\models\Article;

class ArticleListForm extends BaseModel
{

    public $limit = 10;
    public $page;


    public function rules()
    {
        return [
            [['limit', 'page'], 'integer'],

        ]; // TODO: Change the autogenerated stub
    }


    public function getList()
    {
        $query = Article::find()->where(['mall_id' => \Yii::$app->mall->id, 'is_delete' => 0]);
        $list = $query->page($pagination, $this->limit, $this->page)->orderBy('sort desc')->asArray()->all();
        foreach ($list as &$item) {
            $item['created_at'] = DateHelper::format($item['created_at']);
        }
        unset($item);
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagination]);
    }

}