<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-10
 * Time: 20:19
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\helpers\ResponseHelper;
use app\models\Admin;
use app\models\AdminAuthority;
use app\models\BaseModel;

class AdminEditSelfInfoForm extends BaseModel
{


    public $name;

    public $mobile;
    public $avatar;

    public $email;
    public $nickname;


    public function rules()
    {
        return [
            [['mobile', 'avatar', 'email', 'nickname'], 'string'],
            [['mobile'], 'string', 'min' => 11, 'max' => 20],
        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return [
            'nickname' => '昵称',
            'mobile' => '手机号'
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $admin = Admin::findOne(['id' => \Yii::$app->admin->identity->id, 'is_delete' => 0]);
        if (!$admin) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, '用户信息不存在');
        }
        if ($this->nickname) {
            $admin->nickname = $this->nickname;
            $admin->name = $admin->nickname;
        }
        if($this->avatar){
           $admin->avatar=$this->avatar;
        }

        if (!$admin->save()) {
            return $this->responseErrorMsg($admin);
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }

}