<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-10
 * Time: 20:19
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\models\Admin;
use app\models\AdminAuthority;
use app\models\Authority;
use app\models\BaseModel;

class AdminListForm extends BaseModel
{

    public $limit;
    public $page;

    public function rules()
    {
        return [
            [['page', 'limit'], 'integer'],
            [['limit'], 'default', 'value' => 10],
            [['page'], 'default', 'value' => 1],
        ]; // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorMsg();
        }
        /**
         * @var Admin $admin
         */

        $query = Admin::find()->where(['is_delete' => 0]);
        $query->andWhere(['mch_id' => 0]);
        $list = $query->page($pagination, $this->limit, $this->page)->orderBy('id asc')->select('username,nickname,avatar,authority_id,email,mobile,base_color,active_color,side_mode,id')->asArray()->all();
        foreach ($list as &$item) {
            $item['admin_type_name'] = Admin::ADMIN_TYPE[$item['admin_type']];
            if ($item['is_has_expire']) {
                $item['end_at_time'] = date('Y-m-d H:i:s', $item['end_at']);
            }
            $authority = Authority::findOne(['authority_id' => $item['authority_id'], 'is_delete' => 0]);
            if ($authority) {
                $item['authority'] = $authority->attributes;
            }
            $authorities = Authority::find()->alias('a')->innerJoin(['aa' => AdminAuthority::tableName()], 'aa.authority_id=a.authority_id')->andWhere(['aa.admin_id' => $item['id']])->orderBy('id asc')->asArray()->all();
            $item['authorities'] = $authorities;
        }
        unset($item);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagination]);
    }

}