<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-10
 * Time: 20:19
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\helpers\ResponseHelper;
use app\models\Admin;
use app\models\AdminAuthority;
use app\models\AdminRole;
use app\models\BaseModel;

class AdminDeleteForm extends BaseModel
{
    public $id;


    public function rules()
    {
        return [
            [['id'], 'required'],

        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorMsg();
        }
        $admin = Admin::findOne(['id' => $this->id, 'is_delete' => 0]);
        if (!$admin) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '用户不存在');
        }
        if ($admin->admin_type == Admin::ADMIN_TYPE_SUPER) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, '总账户不可删除');
        }
        $admin->is_delete = 1;
        if (!$admin->save()) {
            return $this->responseErrorMsg($admin);
        }

        AdminRole::deleteAll(['admin_id' => $admin->id]);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '删除成功');
    }

}