<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2021-06-11
 * Time: 8:16
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\helpers\JobHelper;
use app\helpers\ResponseHelper;
use app\jobs\CheckQueueJob;
use app\models\BaseModel;

class CheckQueueForm extends BaseModel
{

    public $queue_id;

    public function rules()
    {
        return [

            [['queue_id'], 'integer'],

        ]; // TODO: Change the autogenerated stub
    }

    public function createJob()
    {
        $id = JobHelper::push(new CheckQueueJob());
        $command = \Yii::$app->basePath . '/yii queue/listen';
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['queue_id' => $id, 'command' => $command, 'path' => \Yii::$app->basePath]);
    }

    public function checkJob()
    {
        if (\Yii::$app->queue->isDone($this->queue_id)) {
            return ResponseHelper::send(ApiCode::CODE_SUCCESS, '任务已完成！', ['is_ok' => 1]);
        }
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '任务未完成！', ['is_ok' => 0]);
    }


}