<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-29
 * Time: 1:45
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\helpers\MallMenuHelper;
use app\helpers\OptionHelper;
use app\helpers\ResponseHelper;
use app\models\Admin;
use app\models\BaseModel;
use app\models\Mall;
use app\models\MallPlugin;
use function Sodium\add;

class MallInfoForm extends BaseModel
{
    public $mall_id;

    public function rules()
    {
        return [[['mall_id'], 'integer']]; // TODO: Change the autogenerated stub
    }


    public function search()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        /**
         * @var Admin $admin
         */

        $mall = Mall::findOne(['id' => $this->mall_id, 'is_delete' => 0]);
        if (!$mall) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '商城不存在！');
        }
        if ($mall->is_expire) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '商城已过期！');
        }
        if ($mall->is_stop) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '商城被禁用！');
        }
        if ($admin->admin_type != Admin::ADMIN_TYPE_SUPER) {
            if ($admin->admin_type == Admin::ADMIN_TYPE_FOUNDER) {
                if ($admin->id != $mall->admin_id) {
                    return $this->apiResponse(ApiCode::CODE_FAIL, '您不是该商城的管理员！');
                }
            }
            if ($admin->admin_type == Admin::ADMIN_TYPE_OPERATOR) {
                if ($admin->created_by != $mall->admin_id) {
                    return $this->apiResponse(ApiCode::CODE_FAIL, '您不是该商城的操作员！');
                }
            }
        }
        if (\Yii::$app->admin->identity->admin_type == Admin::ADMIN_TYPE_SUPER) {//超级管理员
            return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['mall' => $mall->attributes]);
        }
        if (\Yii::$app->admin->identity->admin_type == Admin::ADMIN_TYPE_OPERATOR && \Yii::$app->admin->identity->mch_id == 0) {//操作员
            return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['mall' => $mall->attributes]);
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['mall' => $mall->attributes]);
    }

    public function getInfo()
    {
        $mall = Mall::findOne(['id' => $this->mall_id, 'is_delete' => 0]);
        if (!$mall) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '商城不存在！');
        }
        $plugins = MallPlugin::find()->andWhere(['mall_id' => $this->mall_id, 'is_delete' => 0])->select('plugin')->column();
        if (!$plugins) {
            $plugins = [];
        }
        $mall = $mall->attributes;
        $mall['plugins'] = $plugins;
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['mall' => $mall]);
    }
}