<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-10
 * Time: 20:19
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\models\Admin;
use app\models\AdminMall;
use app\models\BaseModel;
use app\models\Mall;

class MallListForm extends BaseModel
{

    public $limit;
    public $page;

    public function rules()
    {
        return [
            [['page', 'limit'], 'integer'],
            [['limit'], 'default', 'value' => 10],
            [['page'], 'default', 'value' => 1],
        ]; // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorMsg();
        }
        /**
         * @var Admin $admin
         */
        $admin = \Yii::$app->admin->identity;
        if (!$admin) {
            return $this->apiResponse(ApiCode::CODE_NOT_LOGIN, '请先登录');
        }
        $admin_id = $admin->id;
        if ($admin->admin_type == 2) {
            $admin_id = $admin->created_by;
        }
        $query = Mall::find()->alias('m')->leftJoin(['a' => AdminMall::tableName()], 'a.mall_id=m.id')->where(['m.is_delete' => 0]);
        if (\Yii::$app->admin->identity->admin_type != Admin::ADMIN_TYPE_SUPER) {
            $query->andWhere(['a.admin_id' => $admin_id]);
        }
        $list = $query->select('m.*')->orderBy('m.created_at DESC')->page($pagination, $this->limit, $this->page)->asArray()->all();
        foreach ($list as &$item) {
            $item['created_at'] = date('Y-m-d H:i:s', $item['created_at']);
            if ($item['is_has_expire']) {
                $item['end_at'] = date('Y-m-d H:i:s', $item['end_at']);
            }
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagination]);
    }

}