<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/4/4
 * Time: 16:45
 * Note:
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\helpers\ResponseHelper;
use app\models\AuthorityMenus;
use app\models\BaseMenu;
use app\models\BaseModel;

class MenuDeleteForm extends BaseModel
{
    public $id;

    public function rules()
    {
        return [
            [['id'],'required']
        ]; // TODO: Change the autogenerated stub
    }

    public function delete(){
        if(!$this->validate()){
            return $this->responseErrorInfo();
        }

        BaseMenu::deleteAll(['id'=>$this->id]);
        AuthorityMenus::deleteAll(['base_menu_id'=>$this->id]);


        return ResponseHelper::send(ApiCode::CODE_SUCCESS,'删除成功');
    }

}