<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2021-08-07
 * Time: 19:16
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\helpers\MallMenuHelper;
use app\helpers\OptionHelper;
use app\helpers\ResponseHelper;
use app\helpers\SerializeHelper;
use app\models\BaseModel;
use yii\helpers\ArrayHelper;

class MenuForm extends BaseModel
{

    public $admin_id;

    public function rules()
    {
        return [
            [['admin_id'], 'integer'],
        ]; // TODO: Change the autogenerated stub
    }

    public function getSetting()
    {
        $check_keys = OptionHelper::get('mall_menus_check_keys_' . $this->admin_id);
        $menu_list = MallMenuHelper::defaultMenuList();
        if (is_array($check_keys)&&count($check_keys)) {
            foreach ($menu_list as $item) {
                if (is_array($check_keys) && ArrayHelper::isIn($item['path'], $check_keys)) {
                    $item['is_checked'] = true;
                }
                if ($item['children'] && count($item['children'])) {
                    foreach ($item['children'] as &$child) {
                        if (is_array($check_keys) && ArrayHelper::isIn($child['path'], $check_keys)) {
                            $child['is_checked'] = true;
                        }
                    }
                    unset($child);
                }
            }
            unset($item);
        } else {
            $check_keys = MallMenuHelper::defaultCheckKeys();
        }
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['menus' => $menu_list, 'check_keys' => is_array($check_keys) ? array_values($check_keys) : []]);
    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2021-08-07
     * @Time: 22:58
     * @Note:获取当前用户的菜单
     * @return array
     */
    public function getMenus()
    {
        if (\Yii::$app->admin->identity->admin_type == 0) {
            return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['menus' => MallMenuHelper::defaultMenuList()]);
        }
        $menu_list = OptionHelper::get('mall_user_menus_' . $this->admin_id);
        if ($menu_list) {
            return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['menus' => $menu_list]);
        }
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['menus' => []]);
    }

    public function getAdminMenus()
    {
        if (\Yii::$app->admin->identity->admin_type == 0) {
            return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['is_admin' => 1]);
        }
        $check_keys = OptionHelper::get('mall_menus_check_keys_' . \Yii::$app->admin->identity->id);
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['is_admin' => 0, 'check_keys' => $check_keys]);
    }

}