<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/4/4
 * Time: 16:27
 * Note:
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\helpers\ResponseHelper;
use app\models\Admin;
use app\models\BaseModel;

class PasswordResetForm extends BaseModel
{
    public $id;

    public function rules()
    {
        return [
            [['id'], 'required'],
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $admin = Admin::getOne($this->id);
        if (!$admin) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, '用户不存在');
        }
        $admin->password = \Yii::$app->security->generatePasswordHash('123456');
        if (!$admin->save()) {
            return $this->responseErrorMsg($admin);
        }

        return ResponseHelper::send(ApiCode::CODE_SUCCESS,'重置成功!');
    }

}