<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-10
 * Time: 20:19
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\models\Admin;
use app\models\BaseModel;

class PasswordChangeForm extends BaseModel
{
    public $id;

    public $password;

    public $newPassword;

    public function rules()
    {
        return [
            [['password', 'newPassword'], 'required'],
            [['password', 'newPassword'], 'string', 'max' => 64],

        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        /**
         * @var Admin $admin
         */
        $admin = \Yii::$app->admin->identity;
        if (!$admin) {
            return $this->apiResponse(ApiCode::CODE_NOT_LOGIN, '请先登录');
        }
        if (!\Yii::$app->security->validatePassword($this->password, $admin->password)) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '原密码不正确!');
        }
        $admin->password = \Yii::$app->security->generatePasswordHash($this->newPassword);
        if (!$admin->save()) {
            return $this->responseErrorMsg($admin);
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }

}