<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-29
 * Time: 11:21
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\models\BaseModel;

class PluginForm extends BaseModel
{
    public $name;
    public $logo;

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['name', 'logo'], 'string']
        ]; // TODO: Change the autogenerated stub
    }


    public function install()
    {

        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        /**
         * 1、下载代码
         */


        try {
            $res = \Yii::$app->plugin->install($this->name);
        } catch (\Exception $e) {
            return $this->apiResponse(ApiCode::CODE_FAIL, $e->getMessage());
        }
        if (!$res) {
            return $this->apiResponse(ApiCode::CODE_SUCCESS, '安装失败');
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '安装成功');
    }

    public function uninstall()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $plugin = \app\models\Plugin::findOne(['name' => $this->name, 'is_delete' => 0]);
        if (!$plugin) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '插件未安装或不存在！');
        }
        $plugin->is_delete = 1;
        if (!$plugin->save()) {
            return $this->responseErrorMsg($plugin);
        }

        return $this->apiResponse(ApiCode::CODE_SUCCESS, '卸载成功');

    }


    public function setLogo()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $plugin = \app\models\Plugin::findOne(['name' => $this->name, 'is_delete' => 0]);
        if (!$plugin) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '插件未安装或不存在！');
        }

        if (!$this->logo) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '请选择logo');
        }
        $plugin->logo = $this->logo;
        if (!$plugin->save()) {
            return $this->responseErrorMsg($plugin);
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2020-11-22
     * @Time: 17:15
     * @Note:插件更新
     */
    public function update()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        try {
            $res = \Yii::$app->plugin->update($this->name);
        } catch (\Exception $e) {
            return $this->apiResponse(ApiCode::CODE_FAIL, $e->getMessage());
        }
        if (!$res) {
            return $this->apiResponse(ApiCode::CODE_SUCCESS, '安装失败');
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '安装成功');
    }
}