<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-12-18
 * Time: 21:13
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\helpers\CacheHelper;
use app\helpers\OptionHelper;
use app\models\Admin;
use app\models\BaseModel;
use app\models\Mall;

class RegisterForm extends BaseModel
{

    public $mobile;

    public $name;
    public $username;
    public $password;
    public $sms_code;


    public function rules()
    {
        return [
            [['name', 'username', 'password', 'mobile', 'sms_code'], 'required'],
            [['name', 'username', 'password'], 'string', 'max' => 20],
            [['mobile'], 'string', 'max' => 11],
        ]; // TODO: Change the autogenerated stub
    }


    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $site_setting = OptionHelper::get('site_setting', 0);
        if (!$site_setting || !$site_setting['is_register']) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '系统未开启注册!');
        }

        $code = CacheHelper::get('sys_auth_code' . $this->mobile);
        if (!$code || $code != $this->sms_code) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '验证码不正确!');
        }
        CacheHelper::remove('sys_auth_code' . $this->mobile);

        $admin = Admin::findOne(['mobile' => $this->mobile]);
        if ($admin) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '已存在该手机号的用户');
        }
        $admin = Admin::findOne(['username' => $this->username]);
        if ($admin) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '用户名已存在，请换一个试试');
        }

        $t = \Yii::$app->db->beginTransaction();
        $admin = new Admin();
        $admin->name = $this->name;
        $admin->username = $this->username;
        $admin->mobile = $this->mobile;
        $admin->password = \Yii::$app->security->generatePasswordHash($this->password);
        $admin->mall_count = 1;
        $admin->admin_type = 1;
        //需要配置试用多久
        if (!$admin->save()) {
            $t->rollBack();
            return $this->responseErrorMsg($admin);
        }
        $mall = new Mall();
        $mall->admin_id = $admin->id;
        $mall->name = $this->name . '的商城';
        if ($site_setting['try_day']) {
            $mall->is_has_expire = 1;
            $mall->end_at = time() + $site_setting['try_day'] * 3600;
        }
        if (!$mall->save()) {
            $t->rollBack();
            return $this->apiResponse(ApiCode::CODE_FAIL, '注册失败，请稍后重试');
        }
        $t->commit();
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '注册成功');
    }

}