<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-12-18
 * Time: 21:45
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\helpers\OptionHelper;
use app\models\BaseModel;

class SmsForm extends BaseModel
{

    public $access_key_id;
    public $access_key_secret;
    public $sign_name;
    public $auth_code_tpl;
    public $auth_code_name;


    public function rules()
    {
        return [
            [['access_key_id', 'access_key_secret', 'sign_name', 'auth_code_tpl', 'auth_code_name'], 'string'],
            [['access_key_id', 'access_key_secret', 'sign_name', 'auth_code_tpl', 'auth_code_name'], 'filter', 'filter' => 'trim'],

        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {

        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

       $res= OptionHelper::set('sys_sms_setting', $this->attributes);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功',['res'=>$res]);
    }

    public function search()
    {
        $res = OptionHelper::get('sys_sms_setting');
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['setting' => $res]);
    }
}