<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-10
 * Time: 21:37
 */

namespace app\forms\admin;


use app\core\ApiCode;
use app\helpers\OptionHelper;
use app\models\Admin;
use app\models\BaseModel;
use app\models\Option;

class SystemEditForm extends BaseModel
{


    public $logo;
    public $name;
    public $login_bg;
    public $manage_bg;
    public $copyright_text;
    public $icp;
    public $copyright_url;
    public $keyword;

    public function rules()
    {
        return [
            [['name', 'logo', 'manage_bg', 'login_bg', 'copyright_text', 'icp', 'copyright_url', 'keyword'], 'string', 'max' => 256]
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        /**
         * @var Admin $admin
         */
        $admin = \Yii::$app->admin->identity;
        if (!$admin) {
            return $this->apiResponse(ApiCode::CODE_NOT_LOGIN, '请先登录');
        }
        if ($admin->admin_type != 0) {
            return $this->apiResponse(ApiCode::CODE_NOT_LOGIN, '权限不足');
        }
        OptionHelper::set(Option::NAME_SYS_SETTING, $this->attributes);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }

}