<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/4/21
 * Time: 11:36
 * Note:
 */

class m220508_213620_mall_plugin extends \app\core\Migration
{

    public function safeUp()
    {
        $this->createTable(
            '{{%mall_plugin}}',
            [
                'id' => $this->primaryKey(11),
                'mall_id' => $this->integer(11)->defaultValue(0)->comment('mall_id'),
                'plugin' => $this->string(45)->defaultValue('')->comment('插件名'),
            ]
        );
        parent::safeUp(); // TODO: Change the autogenerated stub
    }
}