<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-23
 * Time: 10:28
 */

namespace app\forms\common\file;


use app\core\ApiCode;
use app\models\BaseModel;
use app\models\File;

class FileMoveForm extends BaseModel
{

    public $ids;
    public $group_id;


    public function rules()
    {
        return [
            [['group_id'], 'integer'],
            [['ids'], 'safe']
        ]; // TODO: Change the autogenerated stub
    }


    public function move()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        if (!is_array($this->ids)) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '请选择要删除的内容');
        }
        $res = File::updateAll(['group_id' => $this->group_id], ['id' => $this->ids]);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['res' => $res]);
    }

}