<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-23
 * Time: 11:21
 */

namespace app\forms\common\file;

use app\core\ApiCode;
use app\models\BaseModel;
use app\models\FileGroup;

class FileGroupListForm extends BaseModel
{


    public $keyword;
    public $is_site;

    public function rules()
    {
        return [[['keyword'], 'string'],
            [['is_site'], 'integer']]; // TODO: Change the autogenerated stub
    }

    public function getList()
    {


        $query = FileGroup::find()->where(['is_delete' => 0]);

        if ($this->is_site) {
            $query = FileGroup::find()->andWhere(['admin_id' => \Yii::$app->admin->identity->id, 'is_site' => $this->is_site,'is_delete'=>0]);
        } else {
            if (\Yii::$app->mall) {
                $query = FileGroup::find()->andWhere(['mall_id' => \Yii::$app->mall->id, 'is_site' => 0,'is_delete'=>0]);
            }
        }

        if ($this->keyword) {
            $query->andWhere(['like', 'name', $this->keyword]);
        }
        $list = $query->asArray()->all();
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['list' => $list]);
    }
}