<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-23
 * Time: 10:28
 */

namespace app\forms\common\file;


use app\core\ApiCode;
use app\models\BaseModel;
use app\models\File;

class FileDeleteForm extends BaseModel
{

    public $ids;


    public function rules()
    {
        return [
            [['ids'], 'safe']
        ]; // TODO: Change the autogenerated stub
    }


    public function delete()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        if (!is_array($this->ids)) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '请选择要删除的内容');
        }
        $list = File::find()->where(['is_delete' => 0])->andWhere(['id' => $this->ids])->all();
        /**
         * @var File[] $list ;
         */
        $i = 0;
        foreach ($list as $item) {
            $i++;
            $item->is_delete = 1;
            $item->save();
            if ($item->location == 'local') {
                if (file_exists($item->path)) {
                    unlink($item->path);
                }
            }
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['res' => $i]);
    }

}