<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-23
 * Time: 10:28
 */

namespace app\forms\common\file;


use app\core\ApiCode;
use app\models\BaseModel;
use app\models\File;

class FileListForm extends BaseModel
{

    public $type;
    public $page;
    public $limit;
    public $keyword;
    public $group_id;
    public $is_site;

    public function rules()
    {
        return [
            [['type', 'keyword'], 'string'],
            [['limit', 'page', 'group_id', 'is_site'], 'integer'],
            [['limit'], 'default', 'value' => 14],
            [['type'], 'default', 'value' => 'image']
        ]; // TODO: Change the autogenerated stub
    }


    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $query = File::find()->where(['is_delete' => 0]);
        if ($this->is_site == 1) {
            $query = $query->andWhere(['admin_id' => \Yii::$app->admin->identity->id, 'is_site' => $this->is_site]);//站点管理页面
        } else {
            if (\Yii::$app->mall) {
                $query = $query->andWhere(['mall_id' => \Yii::$app->mall->id]);//后台管理员请求的
                $query->andWhere(['user_id' => 0]);
                $query->andWhere(['is_site' => 0]);
            }
        }
        $query->andWhere(['type' => $this->type]);
        if ($this->keyword) {
            $query->andWhere(['like', 'name', $this->keyword]);
        }
        if ($this->group_id) {
            $query->andWhere(['group_id' => $this->group_id]);
        }
        $list = $query->page($pagination, $this->limit, $this->page)->orderBy('created_at DESC')->asArray()->all();
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagination]);
    }

}