<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-10
 * Time: 17:00
 */

namespace app\plugins;


use app\controllers\BaseController;
use app\controllers\mall\filters\MallFilter;

class Controller extends BaseController
{
    public $enableCsrfValidation = false;

    public function init()
    {
        $this->request = \Yii::$app->request;
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function behaviors()
    {
        return array_merge(parent::behaviors(), [
            'mallFilter' => MallFilter::class
        ]);// TODO: Change the autogenerated stub
    }

}
