<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/5/4
 * Time: 9:43
 * Note:
 */

namespace app\forms\api\login;


use app\core\ApiCode;
use app\helpers\CacheHelper;
use app\helpers\ResponseHelper;
use app\models\BaseModel;
use app\models\User;

class PasswordResetForm extends BaseModel
{
    public $password;
    public $code;


    public $mobile;

    public function rules()
    {
        return [
            [['code', 'password', 'mobile'], 'string']
        ]; // TODO: Change the autogenerated stub
    }


    public function reset()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $user = User::findOne(['mobile' => $this->mobile, 'is_delete' => 0]);
        if (!$user) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, '账号不存在');
        }
        //验证手机号
        $code = CacheHelper::get('sms_code' . $this->mobile);
        if ($code != $this->code) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, '验证码不正确!');
        }
        $user->password = \Yii::$app->security->generatePasswordHash($this->password);
        if (!$user->save()) {
            return $this->responseErrorMsg($user);
        }
        CacheHelper::remove('sms_code' . $this->mobile);
        return ResponseHelper::send(ApiCode::CODE_SUCCESS,'密码修改成功，去登录吧！');
    }

}