<?php

namespace app\mongo;

use app\helpers\DateHelper;
use Yii;
use yii\mongodb\Exception;

/**
 * This is the model class for collection "jxmall_admin_action_log".
 *
 * @property \MongoDB\BSON\ObjectID|string $_id
 * @property mixed $mall_id
 * @property mixed $admin_id
 * @property mixed $before_update
 * @property mixed $after_update
 * @property mixed $remarks
 * @property mixed $updated_at
 * @property mixed $created_at
 * @property mixed $deleted_at
 * @property mixed $is_delete
 * @property mixed $created_time
 * @property mixed $model
 * @property mixed $model_id
 */
class JxmallAdminActionLog extends BaseActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function collectionName()
    {
        return 'jxmall_admin_action_log';
    }

    /**
     * {@inheritdoc}
     */
    public function attributes()
    {
        return [
            '_id',
            'mall_id',
            'admin_id',
            'before_update',
            'after_update',
            'remarks',
            'updated_at',
            'created_at',
            'deleted_at',
            'created_time',
            'is_delete',
            'model',
            'model_id',
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['mall_id', 'admin_id', 'before_update', 'after_update', 'remarks', 'updated_at', 'created_time', 'created_at', 'deleted_at', 'is_delete', 'model', 'model_id'], 'safe']
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            '_id' => 'ID',
            'mall_id' => 'Mall ID',
            'admin_id' => 'Admin ID',
            'before_update' => 'Before Update',
            'after_update' => 'After Update',
            'remarks' => 'Remarks',
            'updated_at' => 'Updated At',
            'created_at' => 'Created At',
            'deleted_at' => 'Deleted At',
            'is_delete' => 'Is Delete',
            'model' => 'Model',
            'created_time' => 'created_time',
            'model_id' => 'Model ID',
        ];
    }



    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub
    }
}
