<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/4/20
 * Time: 17:48
 * Note:
 */

namespace app\core;


class Migration extends \yii\db\Migration
{

    public function init()
    {
        $this->db = 'db';
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function createTable($table, $columns, $options = null)
    {
        $default_columns = [
            'is_delete' => $this->tinyInteger(1)->notNull()->defaultValue(0)->comment('是否删除'),
            'created_at' => $this->integer(11)->null()->defaultValue(0)->comment('创建时间戳'),
            'updated_at' => $this->integer(11)->null()->defaultValue(0)->comment('更新时间'),
            'deleted_at' => $this->integer(11)->null()->defaultValue(0)->comment('删除时间'),
            'created_time' => $this->timestamp()->notNull()->defaultExpression("CURRENT_TIMESTAMP")->comment('创建时间'),
            'updated_time' => $this->timestamp()->null()->comment('更新时间'),
            'deleted_time' => $this->timestamp()->null()->comment('删除时间'),
        ];

        $columns = array_merge($columns, $default_columns);
        $tableOptions = 'ENGINE=InnoDB CHARSET=utf8mb4';
        parent::createTable($table, $columns, $options??$tableOptions); // TODO: Change the autogenerated stub
    }
}