<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2021/12/18
 * Time: 10:00
 * Note:
 */

namespace app\forms\api\finance;


use app\core\ApiCode;
use app\helpers\BalanceLogHelper;
use app\helpers\ResponseHelper;
use app\models\BaseModel;
use app\models\User;
use yii\base\Exception;

class BalanceTransferForm extends BaseModel
{


    public $target_id;
    public $money;


    public function rules()
    {
        return [
            [['target_id'], 'integer'],
            [['money'], 'number'],
            [['target_id', 'money'], 'required'],
        ]; // TODO: Change the autogenerated stub
    }


    /**
     * Created by PhpStorm.
     * User：ganxi
     * Date：2021/12/18
     * Time：10:00
     * Note：余额转赠
     */

    public function transfer()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $target = User::getBaseInfo($this->target_id);
        if (!$target) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, '用户不存在！');
        }
        if($this->money<=0){

            return ResponseHelper::send(ApiCode::CODE_FAIL,'输入金额不正确！');
        }
        try {
            $res = BalanceLogHelper::sub(\Yii::$app->user->identity->getId(), $this->money, '转帐给：' . $target->nickname, \Yii::$app->user->identity->getId(), $target->id);
        } catch (Exception $e) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, $e->getMessage());
        }
        if ($res === true) {
            BalanceLogHelper::add($target->id, $this->money, '收到转账，来自用户：' . \Yii::$app->user->identity->nickname, \Yii::$app->user->identity->getId(), $target->id);
        } else {
            \Yii::warning('不够钱还转账了吗？');
        }

        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '转账成功');
    }


}
