<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-11-17
 * Time: 15:30
 */

namespace app\forms\api\finance;


use app\core\ApiCode;
use app\helpers\DateHelper;
use app\models\BalanceLog;
use app\models\BaseModel;
use app\models\IntegralLog;

class BalanceLogListForm extends BaseModel
{

    public $status;
    public $page;
    public $limit;

    public function rules()
    {
        return [
            [['page', 'limit', 'status'], 'integer'],
            [['limit'], 'default', 'value' => 20]
        ]; // TODO: Change the autogenerated stub
    }

    public function getList()
    {

        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        $query = BalanceLog::find()->where(['user_id' => \Yii::$app->user->identity->id, 'is_delete' => 0]);

        if ($this->status) {
            $query->andWhere(['type' => $this->status - 1]);
        }

        $list = $query
            ->page($pagination, $this->limit, $this->page)
            ->orderBy('created_at DESC')
            ->asArray()->all();

        foreach ($list as &$item) {
            $item['created_at'] = DateHelper::format($item['created_at']);
        }
        unset($item);


        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagination]);

    }


}