<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-12-28
 * Time: 16:44
 */

namespace app\forms\mall\user;


use app\core\ApiCode;
use app\helpers\ResponseHelper;
use app\models\BaseModel;
use app\models\User;
use EasyWeChat\Kernel\Exceptions\UnboundServiceException;

class ParentChangeForm extends BaseModel
{

    public $parent_id;

    public $user_id;

    public function rules()
    {
        return [
            [['parent_id', 'user_id'], 'integer']]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();

        }
        $user = User::getOne($this->user_id);
        if (!$user) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, '用户不存在');

        }

        if ($this->parent_id) {
            $parent = User::findOne(['id' => $this->parent_id, 'is_inviter' => 1]);
            if (!$parent) {
                return ResponseHelper::send(ApiCode::CODE_FAIL, '推荐人不存在或不具备推广权限');
            }
        }else{
            $this->parent_id=0;

        }

        $user->bindParent($this->parent_id);


        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '修改成功');


    }


}