<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-24
 * Time: 23:46
 */

namespace app\forms\mall\user;


use app\core\ApiCode;
use app\helpers\OptionHelper;
use app\models\BaseModel;

class UserSettingForm extends BaseModel
{
    public $child_type;
    public $is_check;
    public $invite_type;
    public $detail;
    public $list;
    public $goods_ids;
    public $buy_type;
    public $price;
    public function rules()
    {
        return [
            [['list', 'goods_ids'], 'safe'],
            [['price'], 'number'],
            [['child_type', 'is_check', 'invite_type', 'buy_type'], 'integer'],
            [['detail'], 'string']
        ]; // TODO: Change the autogenerated stub
    }


    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        if ($this->invite_type == 1) {
            if (!count($this->goods_ids)) {
                return $this->apiResponse(ApiCode::CODE_FAIL, '请选择商品');
            }
        }

        OptionHelper::set('relation_setting', $this->attributes, $this->mall_id);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功！');
    }

    public function search()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $res = OptionHelper::get('relation_setting', $this->mall_id);
        if ($res) {
            return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功！', ['setting' => $res]);
        }
        return $this->apiResponse(ApiCode::CODE_FAIL, '暂无配置！');
    }
}