<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-18
 * Time: 12:48
 */

namespace app\forms\mall\user;


use app\core\ApiCode;
use app\helpers\IconHelper;
use app\helpers\MallSettingHelper;
use app\models\BaseModel;
use app\models\CommonOrder;
use app\models\Level;
use app\models\User;
use app\models\UserParent;

class UserListForm extends BaseModel
{

    public $page;
    public $limit;
    public $keyword;
    public $user_id;
    public $mobile;
    public $nickname;
    public $parent_id;
    public $level_id;
    public $top_parent_id;


    public function rules()
    {
        return [
            [['keyword', 'nickname', 'mobile'], 'string'],
            [['user_id'], 'integer'],
            [['page', 'limit', 'parent_id', 'level_id', 'top_parent_id'], 'integer'],
        ]; // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $query = User::find()->where(['mall_id' => \Yii::$app->mall->id, 'is_delete' => 0]);
        if ($this->keyword) {
            $query->andWhere(['like', 'nickname', $this->keyword]);
        }
        if ($this->top_parent_id) {
            $uids = UserParent::find()->andWhere(['parent_id' => $this->top_parent_id, 'is_delete' => 0])->select('user_id')->distinct()->column();
            $query->andWhere(['id' => $uids]);
        }
        if ($this->parent_id) {
            $query->andWhere(['parent_id' => $this->parent_id]);
        }
        $query->andFilterWhere(['mobile' => $this->mobile, 'id' => $this->user_id]);
        $query->andFilterWhere(['like', 'nickname', $this->nickname]);
        $list = $query->with('inviter')->page($pagination, $this->limit, $this->page)->orderBy('created_at desc')
            ->select('nickname,avatar_url,created_at,money,price,id,level_at,mobile,level,integral,price,total_price,platform,parent_id,is_subscribe,is_inviter')
            ->asArray()->all();
        $logo = MallSettingHelper::getLogo(\Yii::$app->mall->id);
        foreach ($list as &$item) {
            if ($item['level_at']) {
                $item['level_at'] = date('Y-m-d H:i:s', $item['level_at']);
            }
            $item['created_at'] = date('Y-m-d H:i:s', $item['created_at']);
            if ($item['level'] == 0) {
                $item['level'] = '默认等级';
            } else {
                $level = Level::findOne(['mall_id' => \Yii::$app->mall->id, 'level' => $item['level'], 'is_delete' => 0]);
                if ($level) {
                    $item['level'] = $level->name;
                } else {
                    $item['level'] = '默认等级';
                }
            }
            $item['total_order_price'] = CommonOrder::find()->where(['user_id' => $item['id'], 'is_delete' => 0, 'status' => 1])->sum('pay_price');
            $item['order_num'] = CommonOrder::find()->where(['user_id' => $item['id'], 'is_delete' => 0, 'status' => 1])->count();
            if ($item['platform'] == User::PLATFORM_WECHAT) {
                $item['platform_logo'] = IconHelper::wechat();
            }
            if ($item['platform'] == User::PLATFORM_MPWX) {
                $item['platform_logo'] = IconHelper::mpwx();
            }
            if ($item['platform'] == User::PLATFORM_WXAPP) {
                $item['platform_logo'] = IconHelper::wxapp();
            }
            if ($item['platform'] == User::PLATFORM_MOBILE) {
                $item['platform_logo'] = IconHelper::mobile();
            }


            if ($item['inviter']) {
                $item['parent_avatar'] = $item['inviter']['avatar_url'];
                $item['parent_name'] = $item['inviter']['nickname'];
            } else {
                $item['parent_avatar'] = $logo;
                $item['parent_name'] = '平台';
            }
            unset($item['inviter']);
        }
        unset($item);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagination]);
    }
}
