<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-18
 * Time: 22:30
 */

namespace app\forms\mall\user;


use app\core\ApiCode;
use app\models\BaseModel;
use app\models\Level;
use app\models\User;
use app\models\UserUpgradeLog;

class UserLevelChangeForm extends BaseModel
{
    public $user_id;

    public $level;


    public function rules()
    {
        return [
            [['user_id', 'level'], 'integer'],
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $user = User::getUser($this->user_id);
        if (!$user) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '用户不存在！');
        }
        $log = new UserUpgradeLog();
        $log->user_id = $this->user_id;
        $log->before_level_id = $user->level_id;
        $log->reason_by = 3;
        $log->marks = '后台编辑';

        if ($this->level == 0) {
            $user->level = 0;
            $user->level_id = 0;
            $user->is_manual = 1;
            $user->level_at = time();
            if (!$user->save()) {
                return $this->responseErrorMsg($user);
            }
            try {
                $log->mall_id = $user->mall_id;
                $log->after_level_id = $user->level_id;
                if (!$log->save()) {
                    \Yii::warning($log->getFirstErrors());
                }
            } catch (\Exception $exception) {
                \Yii::warning($exception->getMessage());
            }
            return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
        }
        $level = Level::findOne(['level' => $this->level, 'mall_id' => \Yii::$app->mall->id, 'is_delete' => 0]);
        if (!$level) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '等级不存在！');
        }
        if ($user->level != $this->level) {
            $user->level = $this->level;
            $user->level_id = $level->id;
            $user->is_manual = 1;
            $user->level_at = time();
            if (!$user->save()) {
                return $this->responseErrorMsg($user);
            }
        }
        try {
            $log->mall_id = $user->mall_id;
            $log->after_level_id = $user->level_id;
            if (!$log->save()) {
                \Yii::warning($log->getFirstErrors());
            }
        } catch (\Exception $exception) {
            \Yii::warning($exception->getMessage());
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }

}
