<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-13
 * Time: 20:10
 */

namespace app\forms\api\goods;


use app\core\ApiCode;
use app\helpers\SerializeHelper;
use app\models\BaseModel;
use app\models\GoodsComment;

class GoodsCommentForm extends BaseModel
{
    public $data_list;

    public function rules()
    {
        return [[['data_list'], 'required'],
            [['data_list'], 'safe'],
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        $list = SerializeHelper::decode($this->data_list);

        $t = \Yii::$app->db->beginTransaction();


        foreach ($list as $item) {
            $comment = GoodsComment::findOne(['order_id' => $item['order_id'], 'goods_id' => $item['goods_id'], 'is_delete' => 0]);
            if (!$comment) {
                $comment = new GoodsComment();
                $comment->user_id = \Yii::$app->user->identity->id;
                $comment->mall_id = \Yii::$app->mall->id;
                $comment->goods_id = $item['goods_id'];
                $comment->order_id = $item['order_id'];
            }
            $comment->content = $item['content'];
            $comment->pic_list = SerializeHelper::encode($item['pic_list']);
            $comment->grade_level = $item['grade_level'];
            if (!$comment->save()) {
                $t->rollBack();
                return $this->responseErrorMsg($comment);
            }
        }

        $t->commit();
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '评论成功');

    }

}