<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-13
 * Time: 20:52
 */

namespace app\forms\api\goods;


use app\core\ApiCode;
use app\models\BaseModel;
use app\models\GoodsComment;
use app\models\User;

class GoodsCommentListForm extends BaseModel
{

    public $page;
    public $goods_id;

    public $limit;

    public function rules()
    {
        return [
            [['goods_id'], 'required'],
            [['page', 'limit', 'goods_id'], 'integer'],
            [['limit'], 'default', 'value' => 10]
        ]; // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        $total = GoodsComment::find()->where(['goods_id' => $this->goods_id, 'is_delete' => 0])->count();
        $sum = GoodsComment::find()->where(['goods_id' => $this->goods_id, 'is_delete' => 0])->sum('grade_level');
        $sum = intval($sum / $total);

        $list = GoodsComment::find()->alias('c')->leftJoin(['u' => User::tableName()], 'u.id=c.user_id')
            ->where(['c.goods_id' => $this->goods_id, 'c.is_delete' => 0])
            ->select('u.nickname,u.avatar_url,c.*')
            ->page($pagination, $this->limit, $this->page)
            ->orderBy('c.created_at DESC')->asArray()->all();


        foreach ($list as &$item) {
            $item['created_at'] = date('Y-m-d H:i:s', $item['created_at']);
        }

        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagination, 'total' => $total,'sum'=>$sum]);


    }
}