<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/3/15
 * Time: 20:29
 * Note:
 */

namespace app\forms\mall\goods;


use app\core\ApiCode;
use app\helpers\ResponseHelper;
use app\models\BaseModel;
use app\models\GoodsUpDownJob;

class GoodsUpDownJobForm extends BaseModel
{
    public $goods_id;
    public $status;
    public $action_time;

    public function rules()
    {
        return [
            [['goods_id', 'status'], 'integer'],
            [['action_time'], 'string']
        ]; // TODO: Change the autogenerated stub
    }


    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        if (!$this->action_time) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, '请选择时间');
        }
        $job = new GoodsUpDownJob();
        $job->status = $this->status;
        $job->mall_id = $this->mall_id;
        $job->goods_id = $this->goods_id;
        $job->action_time = $this->action_time;
        $job->action_at = strtotime($this->action_time);
        if (!$job->save()) {
            return $this->responseErrorMsg($job);
        }
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '设置成功');
    }

    public function getList()
    {
        $list = GoodsUpDownJob::find()->andWhere(['goods_id' => $this->goods_id, 'is_done' => 0])->orderBy('action_at asc')->asArray()->all();
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['list' => $list]);
    }
}