<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-09-22
 * Time: 22:13
 */

namespace app\controllers\common;


use app\controllers\BaseController;
use app\core\ApiCode;
use app\forms\common\file\FileDeleteForm;
use app\forms\common\file\FileGroupDeleteForm;
use app\forms\common\file\FileGroupEditForm;
use app\forms\common\file\FileGroupListForm;
use app\forms\common\file\FileListForm;
use app\forms\common\file\FileMoveForm;
use app\forms\common\file\FileUploadForm;
use app\helpers\ExpressHelper;
use app\models\Admin;
use app\models\File;
use app\models\Mall;
use app\models\User;
use yii\web\UploadedFile;

class FileController extends BaseController
{
    public $enableCsrfValidation = false;


    public function beforeAction($action)
    {

        // TODO: Change the autogenerated stub
        $headers = $this->request->headers;
        \Yii::warning($headers['x-mall-id']);
        if ($headers) {
            if ($headers['x-admin-token']) {
                $admin = Admin::findOne(['is_delete' => 0, 'access_token' => $headers['x-admin-token'], 'is_expire' => 0]);
                if ($admin) {
                    \Yii::$app->admin->login($admin);
                }
            }
            if ($headers['x-mall-id']) {
                $mall = Mall::findOne(['is_delete' => 0, 'id' => $headers['x-mall-id']]);
                if ($mall) {
                    \Yii::$app->setMall($mall);
                }
            }
            if ($headers['x-access-token']) {
                $user = User::findOne(['is_delete' => 0, 'access_token' => $headers['x-access-token']]);
                if ($user) {
                    \Yii::$app->user->login($user);
                }
            }
        }


        parent::beforeAction($action);
        return true;
    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2020-09-23
     * @Time: 12:15
     * @Note:文件列表
     * @return \yii\web\Response
     */
    public function actionList()
    {
        $form = new FileListForm();
        $form->attributes = $this->request->get();
        return $this->asJson($form->getList());
    }


    public function actionDelete()
    {
        $form = new FileDeleteForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->delete());
    }

    public function actionMove()
    {
        $form = new FileMoveForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->move());
    }


    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2020-09-22
     * @Time: 22:32
     * @Note:图片上传
     */
    public function actionUpload()
    {
        $form = new FileUploadForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->saveFile());
    }

    public function actionUserUpload()
    {
        $form = new FileUploadForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->saveUserFile());
    }


    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2020-09-23
     * @Time: 11:04
     * @Note:编辑文件组
     */
    public function actionGroupEdit()
    {
        $form = new FileGroupEditForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->save());
    }

    public function actionGroupList()
    {
        $form = new FileGroupListForm();
        $form->attributes = $this->request->get();
        return $this->asJson($form->getList());
    }

    public function actionGroupDelete()
    {
        $form = new FileGroupDeleteForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->delete());
    }


}
