<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-11-29
 * Time: 12:42
 */

namespace app\forms\mall\poster;


use app\core\ApiCode;
use app\helpers\OptionHelper;
use app\helpers\PosterHelper;
use app\helpers\SerializeHelper;
use app\models\BaseModel;

class GoodsPosterForm extends BaseModel
{

    public $data;

    public function rules()
    {
        return [

            [['data'], 'string']

        ]; // TODO: Change the autogenerated stub
    }


    public function search()
    {
        $setting = OptionHelper::get('goods_poster_setting', \Yii::$app->mall->id);
        if (!$setting) {
            $setting = PosterHelper::getDefault()['goods'];
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['setting' => $setting]);
    }

    public function save()
    {

        if (!$this->data) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '数据不能为空');
        }

        $data = SerializeHelper::decode($this->data);
        OptionHelper::set('goods_poster_setting', $data, \Yii::$app->mall->id);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功 ');
    }
}