<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/4/19
 * Time: 14:30
 * Note:
 */

namespace app\jobs\goods;


use app\jobs\Job;
use app\models\CommonOrderDetail;
use app\models\Goods;

class GoodsSalesJob extends Job
{
    public $common_order_detail_id;
    public $status;

    public function execute($queue)
    {
        \Yii::warning('处理销量');
        $commonOrderDetail = CommonOrderDetail::getOne($this->common_order_detail_id);
        if (!$commonOrderDetail) {
            return;
        }
        /**
         * @var Goods $goods
         */
        $goods = $commonOrderDetail->goods;
        if (!$goods) {
            return;
        }
        $virtual_sales = $goods->virtual_sales ?? 0;
        $sales = $goods->sales ?? 0;

        if ($this->status == 1) {
            \Yii::warning('加销量');
            $virtual_sales += $commonOrderDetail->num;
            $sales += $commonOrderDetail->num;
        } else {
            \Yii::warning('减销量');
            $virtual_sales -= $commonOrderDetail->num;
            $sales -= $commonOrderDetail->num;
            $virtual_sales = $virtual_sales > 0 ? $virtual_sales : 0;
            $sales = $sales > 0 ? $virtual_sales : 0;
        }

        Goods::updateAll(['virtual_sales' => $virtual_sales, 'sales' => $sales], ['id' => $goods->id]);
        //parent::execute($queue); // TODO: Change the autogenerated stub
    }
}