#!/usr/bin/env php
<?php
/**
 * Yii console bootstrap file.
 *
 * @link http://www.yiiframework.com/
 * @copyright Copyright (c) 2008 Yii Software LLC
 * @license http://www.yiiframework.com/license/
 */
defined('IN_IA') or define('IN_IA', true);
require __DIR__ . '/vendor/autoload.php';
$config = require __DIR__ . '/config/console.php';
$application = new app\core\ConsoleApplication($config);
$exitCode = $application->run();
exit($exitCode);
