<?php

use yii\log\Logger;

/**
 * IDE friendly
 * 此文件没有任何作用，只是为了IDE友好提示而已
 */
class Yii extends \yii\BaseYii
{
    /**
     * @var Application the application instance
     */
    public static $app;

    public static function warning($message, $category = 'application')
    {
        if (!is_dir(Yii::$app->runtimePath . '/logs')) {
            \yii\helpers\FileHelper::createDirectory(Yii::$app->runtimePath . '/logs', 0755);
        }
        $file = Yii::$app->runtimePath . '/logs/' . date('Y-m-d') . '.log';
        if (file_exists($file)) {
            if (!is_writeable($file)) {
                chmod($file, 0755);
            }
        }
        parent::warning($message, $category); // TODO: Change the autogenerated stub
        $log = new \app\mongo\JxmallLog();
        $log->message = $message;
        $log->type = 'warning';
        $ts = debug_backtrace(DEBUG_BACKTRACE_IGNORE_ARGS);
        array_pop($ts);
        $log->trace = $ts;
        if (count($ts)) {
            $log->file = $ts[0]['file'];
            $log->line = $ts[0]['line'];
        }
        $log->save();
    }
}

spl_autoload_register(['Yii', 'autoload'], true, true);
Yii::$classMap = require __DIR__ . '/vendor/yiisoft/yii2/classes.php';
Yii::$container = new yii\di\Container();

/**
 * Class BaseApplication
 * Used for properties that are identical for both WebApplication and ConsoleApplication
 * @property \app\models\User $user
 * @property \yii\web\User $admin
 * @property \yii\queue\Queue $queue
 * @property \jianyan\easywechat\Wechat $wechat
 * @property \app\components\Plugin $plugin
 * @property \yii\redis\Connection $redis
 * @property \app\core\Connection $db
 * @property \yii\mongodb\Connection $mongodb
 * @property \app\models\Mall $mall
 * @property \app\components\JoinPay $joinPay
 */
abstract class Application extends yii\base\Application
{
    /**
     * @return \app\models\User
     */
    abstract function getUser();

    /**
     * @return \app\models\Admin
     */
    abstract function getAdmin();

}
