<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/3/14
 * Time: 8:37
 * Note:
 */

namespace app\forms\api\user;


use app\core\ApiCode;
use app\helpers\ResponseHelper;
use app\models\BaseModel;
use app\models\Feedback;

class FeedbackForm extends BaseModel
{
    public $content;
    public function rules()
    {
        return [
            [['content'], 'string', 'max' => 2048]
        ]; // TODO: Change the autogenerated stub
    }
    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $model = new Feedback();
        $model->user_id = \Yii::$app->user->identity->getId();
        $model->mall_id = $this->mall_id;
        $model->attributes = $this->attributes;
        if (!$model->save()) {
            return $this->responseErrorMsg($model);
        }
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '提交成功！');
    }

}