<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2021-01-03
 * Time: 15:37
 */

namespace app\forms\api\user;


use app\core\ApiCode;
use app\helpers\ResponseHelper;
use app\models\BaseModel;
use app\models\Goods;
use app\models\GoodsFootmark;

class GoodsFootmarkListForm extends BaseModel
{
    public $page;
    public $limit = 10;

    public function rules()
    {
        return [
            [['limit', 'page'], 'integer'],
        ]; // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $query = GoodsFootmark::find()->alias('f')
            ->where(['f.mall_id' => \Yii::$app->mall->id, 'f.is_delete' => 0, 'f.user_id' => \Yii::$app->mall->id])
            ->leftJoin(['g' => Goods::tableName()], 'g.id=f.goods_id');
        $list = $query->page($pagionation, $this->limit, $this->page)
            ->select('g.*')
            ->asArray()->all();
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagionation]);
    }

}