<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-11-12
 * Time: 0:02
 */

namespace app\controllers\api;


use app\controllers\api\filters\LoginFilter;
use app\forms\api\coupon\CouponCenterForm;
use app\forms\api\coupon\CouponForm;

class CouponController extends Controller
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(),
            ['login' => ['class' => LoginFilter::class]]
        ); // TODO: Change the autogenerated stub
    }

    public function actionCouponCenter()
    {

        $form = new CouponCenterForm();

        return $this->asJson($form->search());

    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2020-11-12
     * @Time: 0:03
     * @Note: 领取优惠券
     */
    public function actionCouponReceive()
    {
        $form = new CouponForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->receive());
    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2020-11-12
     * @Time: 0:35
     * @Note: 用户优惠券
     * @return \yii\web\Response
     */
    public function actionUserCouponList()
    {
        $form = new CouponForm();
        $form->attributes = $this->request->get();
        return $this->asJson($form->getUserCouponList());


    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2020-11-12
     * @Time: 0:35
     * @Note: 平台优惠券
     * @return \yii\web\Response
     */
    public function actionCouponList()
    {
        $form = new CouponForm();
        $form->attributes = $this->request->get();
        return $this->asJson($form->getCouponList());

    }

}