<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-13
 * Time: 22:33
 */

namespace app\controllers\api;


use app\forms\api\login\LoginForm;
use app\forms\api\login\MobileSignInForm;
use app\forms\api\login\PasswordResetForm;
use app\forms\api\login\SmsCodeForm;
use app\forms\api\login\WechatUserInfoForm;
use app\helpers\WechatHelper;

class LoginController extends Controller
{

    public function beforeAction($action)
    {
        WechatHelper::init(\Yii::$app->mall->id);

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2020-10-13
     * @Time: 22:33
     * @Note:公众号登录
     */
    public function actionWechat()
    {
        $form = new LoginForm();
        $form->attributes = $this->request->get();
        return $this->asJson($form->loginByWechat());
    }

    public function actionWechatUserInfo()
    {

        $form = new LoginForm();
        $form->attributes = $this->request->get();
        return $this->asJson($form->getWechatUserInfo());
    }


    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2022-03-24
     * @Time: 20:46
     * @Note: 小程序登录
     * @return \yii\web\Response
     * @throws \yii\base\Exception
     */
    public function actionMpwx()
    {
        $form = new LoginForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->loginByMpwx());

    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2022-03-24
     * @Time: 20:46
     * @Note:app登录
     * @return \yii\web\Response
     */
    public function actionApp()
    {
        $form = new LoginForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->loginByApp());
    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2022-03-24
     * @Time: 20:46
     * @Note:解析微信用户信息
     * @return \yii\web\Response
     */
    public function actionMpwxUserInfo()
    {
        $form = new WechatUserInfoForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->mpwxUser());
    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2022-03-24
     * @Time: 20:46
     * @Note:获取短信验证码
     * @return \yii\web\Response
     */
    public function actionSmsCode()
    {
        $form = new SmsCodeForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->getCode());
    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2022-03-24
     * @Time: 20:53
     * @Note:手机号注册
     */
    public function actionSign()
    {
        $form = new MobileSignInForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->signIn());
    }


    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2022-03-24
     * @Time: 21:14
     * @Note:手机号登录
     */
    public function actionMobile()
    {
        $form = new LoginForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->loginByMobile());
    }

    /**
     * Created by PhpStorm.
     * User：ganxi
     * Date：2022/5/4
     * Time：9:43
     * Note：重置密码
     */
    public function actionPasswordReset()
    {
        $form = new PasswordResetForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->reset());
    }
}