<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-13
 * Time: 19:20
 */

namespace app\controllers\api;


use app\controllers\api\filters\LoginFilter;
use app\forms\common\file\FileUploadForm;

class UploadController extends Controller
{
    public function behaviors()
    {
        return array_merge(parent::behaviors(),
            ['login' => LoginFilter::class]
        ); // TODO: Change the autogenerated stub
    }

    public function actionUpload()
    {
        $form = new FileUploadForm();
        $form->attributes = $this->request->post();
        return $this->asJson($form->saveUserFile());
    }
}