<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-13
 * Time: 22:40
 */

namespace app\controllers\api;


use app\core\ApiCode;
use app\forms\api\wechat\WechatForm;
use app\helpers\OptionHelper;
use app\helpers\WechatHelper;

class WechatController extends Controller
{


    public function beforeAction($action)
    {
        WechatHelper::init(\Yii::$app->mall->id);

        return parent::beforeAction($action); // TODO: Change the autogenerated stub
    }

    /**
     * @Author: 动力宇宙 ganxiaohao
     * @Date: 2020-10-13
     * @Time: 22:40
     * @Note:
     */
    public function actionSetting()
    {
        $setting = OptionHelper::get('platform_wechat', \Yii::$app->mall->id);
        if (!$setting) {
            return $this->asJson(['code' => ApiCode::CODE_FAIL, 'msg' => '未配置平台信息']);
        }
        return $this->asJson(['code' => ApiCode::CODE_SUCCESS, 'msg' => '', 'data' => ['appid' => $setting['appid']],'setting'=>$setting]);
    }

    public function actionJssdk()
    {

        $form = new WechatForm();
        $form->attributes = $this->request->get();
        return $this->asJson($form->getJssdk());
    }

}