<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-12-18
 * Time: 9:34
 */

namespace app\forms\mall\mall;


use app\core\ApiCode;
use app\helpers\OptionHelper;
use app\helpers\SerializeHelper;
use app\models\BaseModel;

class AlertAdvForm extends BaseModel
{
    public $data;


    public function rules()
    {
        return [
            [['data'], 'string']
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        OptionHelper::set('alert_data', SerializeHelper::decode($this->data), \Yii::$app->mall->id);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }

    public function search()
    {
        $alert_data = OptionHelper::get('alert_data', \Yii::$app->mall->id);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['alert_data' => $alert_data]);
    }


}