<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/3/23
 * Time: 9:00
 * Note:
 */

namespace app\forms\mall\mall;


use app\core\ApiCode;
use app\helpers\OptionHelper;
use app\helpers\ResponseHelper;
use app\models\BaseModel;

class CheckingForm extends BaseModel
{

    public $ios;
    public $mpwx;
    public $android;
    public $is_enabled;
    public $api_url;


    public function rules()
    {
        return [
            [['is_enabled'], 'integer'],
            [['ios', 'mpwx', 'android','api_url'], 'string']
        ]; // TODO: Change the autogenerated stub
    }


    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        OptionHelper::set('checking_versions', $this->attributes, $this->mall_id);
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '保存成功');
    }
    public function search()
    {
        $versions = OptionHelper::get('checking_versions', $this->mall_id);
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['versions' => $versions]);
    }

}