<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/3/14
 * Time: 9:56
 * Note:
 */

namespace app\forms\mall\mall;


use app\core\ApiCode;
use app\helpers\ResponseHelper;
use app\models\BaseModel;
use app\models\Feedback;
use app\models\User;

class FeedbackListForm extends BaseModel
{
    public $page;
    public $limit;

    public function rules()
    {
        return [
            [['page', 'limit'], 'integer'],
        ]; // TODO: Change the autogenerated stub
    }


    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $query = Feedback::find()->alias('f')->leftJoin(['u' => User::tableName()], 'u.id=f.user_id');
        $query->andWhere(['f.mall_id' => \Yii::$app->mall->id, 'f.is_delete' => 0]);
        $list = $query->page($pagination, $this->limit, $this->page)->select('f.*,u.nickname,u.avatar_url')->asArray()->all();
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagination]);
    }
}