<?php
/**
 * Created by PhpStorm.
 * User: ganxi
 * Date: 2022/3/29
 * Time: 14:26
 * Note:
 */

namespace app\forms\mall\mall;


use app\core\ApiCode;
use app\helpers\ResponseHelper;
use app\models\BaseModel;
use app\models\HotImage;
use yii\helpers\Json;

class HotImageForm extends BaseModel
{
    public $id;
    public $pic_url;
    public $data;
    public $name;

    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['data'], 'safe'],
            [['name', 'pic_url'], 'string']
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $model = HotImage::getOne($this->id);
        if (!$model) {
            $model = new HotImage();
            $model->mall_id = $this->mall_id;
        }
        $model->name = $this->name;
        $model->pic_url = $this->pic_url;
        $model->data = Json::encode($this->data);
        if (!$model->save()) {
            return $this->responseErrorMsg($model);
        }
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '保存成功！');
    }

    public function search()
    {

        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $model = HotImage::getOne($this->id);
        if (!$model) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, '未配置数据');
        }
        $info = $model->attributes;
        $info['data'] = Json::decode($info['data']);
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['info' => $info]);
    }

    public function delete()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $model = HotImage::getOne($this->id);
        if (!$model) {
            return ResponseHelper::send(ApiCode::CODE_FAIL, '热土不存在！');
        }
        $model->delete();
        return ResponseHelper::send(ApiCode::CODE_SUCCESS,'删除成功！');
    }

}