<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-15
 * Time: 10:40
 */

namespace app\forms\mall\mall;


use app\core\ApiCode;
use app\helpers\CacheHelper;
use app\helpers\OptionHelper;
use app\models\BaseModel;
use app\models\ExpressSetting;
use app\models\Mall;

class MallSettingForm extends BaseModel
{

    public $name;
    public $logo;
    public $detail;
    public $tel;
    public $over_time;
    public $confirm_time;
    public $complete_time;
    public $receive_name;
    public $receive_address;
    public $receive_mobile;
    public $EBusinessID;//快递鸟参数
    public $AppKey;//快递鸟key
    public $file_location;
    public $about;
    public $access_key_id;
    public $access_key_secret;
    public $sign_name;
    public $is_binding; //是否绑定手机号
    public $show_contact;//显示客服
    public $contact_icon;
    public $show_phone;//显示电话客服
    public $phone_icon;//电话图标
    public $is_home_login;
    public $address;
    public $lon;
    public $lat;
    public $show_nav;
    public $nav_icon;
    public $sms_tpl;
    public $sms_tpl_code;
    public $is_login_mobile;
    public $login_pic;
    public $is_ban_cancel; //禁止取消订单或退款
    public $is_show_add_cart;

    public function rules()
    {
        return [
            [['name'], 'required'],
            [['address'], 'string'],
            [['lon', 'lat'], 'number'],
            [['name', 'sms_tpl', 'sms_tpl_code', 'phone_icon', 'nav_icon', 'contact_icon', 'login_pic', 'about', 'logo', 'detail', 'tel', 'receive_name', 'receive_address', 'receive_mobile', 'EBusinessID', 'AppKey', 'file_location', 'access_key_id', 'access_key_secret', 'sign_name'], 'string'],
            [['over_time', 'is_ban_cancel', 'is_show_add_cart', 'confirm_time', 'complete_time', 'is_binding', 'show_contact', 'show_phone', 'is_home_login', 'show_nav', 'is_login_mobile'], 'integer'],
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $mall = Mall::findOne(\Yii::$app->mall->id);
        if ($this->logo) {
            $mall->logo = $this->logo;
        }
        if ($this->name) {
            $mall->name = $this->name;
        }
        if ($this->detail) {
            $mall->detail = $this->detail;
        }
        if (!$mall->save()) {
            return $this->responseErrorMsg($mall);
        }
        if ($this->EBusinessID && $this->AppKey) {
            $exSetting = ExpressSetting::findOne(['mall_id' => $mall->id, 'is_delete' => 0]);
            if (!$exSetting) {
                $exSetting = new ExpressSetting();
                $exSetting->mall_id = $mall->id;
                $exSetting->kdniao_customer = $this->EBusinessID;
                $exSetting->kdniao_appcode = $this->AppKey;
                $exSetting->save();
            } else {
                $exSetting->kdniao_customer = $this->EBusinessID;
                $exSetting->kdniao_appcode = $this->AppKey;
                $exSetting->save();
            }
        }
        if ($this->file_location) {
            if ($this->file_location != 'local') {
                $location = OptionHelper::get($this->file_location, \Yii::$app->mall->id);
                if ($location) {
                    if ($location['enabled'] == 0) {
                        return $this->apiResponse(ApiCode::CODE_FAIL, '上传位置未启用，请先启用');
                    }
                } else {
                    return $this->apiResponse(ApiCode::CODE_FAIL, '上传位置未配置，请请先配置');
                }
            }
        }
        $setting = array_merge($mall->attributes, $this->attributes);
        OptionHelper::set('mall_setting', $setting, \Yii::$app->mall->id);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }

    public function search()
    {
        $mall_setting = OptionHelper::get('mall_setting', \Yii::$app->mall->id);
        if (!$mall_setting) {
            $mall_setting = \Yii::$app->mall;
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功', ['setting' => $mall_setting]);
    }


}
