<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-11-10
 * Time: 17:26
 */

namespace app\forms\mall\mall;


use app\core\ApiCode;
use app\models\BaseModel;
use app\models\CommonOrder;
use app\models\CommonOrderDetail;
use app\models\Goods;
use app\models\Order;
use app\models\OrderRefund;
use app\models\User;

class MallDataForm extends BaseModel
{

    public $select_date; //1 今日  2 本月  3 年

    public $search_date; //搜索日期范围


    public function rules()
    {
        return [
            [['select_date'], 'integer'],
            [['search_date'], 'safe']
        ]; // TODO: Change the autogenerated stub
    }

    public function search()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $info['send_order'] = Order::find()->where(['mall_id' => $this->mall_id, 'is_delete' => 0])
            ->andWhere(['status' => Order::STATUS_NOT_SEND])
            ->count();
        $info['refund_order'] = OrderRefund::find()->where(['mall_id' => $this->mall_id, 'is_delete' => 0, 'status' => 0])->count();
        $info['user'] = User::find()->where(['mall_id' => $this->mall_id, 'is_delete' => 0])->count();
        $info['customer'] = CommonOrder::find()->where(['mall_id' => $this->mall_id, 'is_delete' => 0,'is_pay'=>1])->andWhere(['!=', 'status', '2'])->groupBy('user_id')->count();
        $info['goods'] = Goods::find()->where(['mall_id' => $this->mall_id, 'is_delete' => 0])->count();
        $info['order'] = CommonOrder::find()->where(['mall_id' => $this->mall_id, 'is_delete' => 0])->andWhere(['!=', 'status', '2'])->count();

        //这些要按照日期来筛选


        $today = strtotime(date('Y-m-d', time()));
        $month = strtotime(date('Y-m', time()));
        $year = strtotime(date('Y-01-01', time()));
        $start = '';
        $end = '';
        if ($this->search_date) {
            $start = strtotime($this->search_date[0]);
            $end = strtotime($this->search_date[1]);


        }
        $query = CommonOrder::find()->where(['mall_id' => $this->mall_id, 'is_delete' => 0, 'status' => 1]);
        if ($this->select_date) {
            if ($this->select_date == 1) {
                $query->andWhere(['>', 'created_at', $today]);
            }
            if ($this->select_date == 2) {
                $query->andWhere(['>', 'created_at', $month]);
            }
            if ($this->select_date == 3) {
                $query->andWhere(['>', 'created_at', $year]);
            }
        }

        if ($this->search_date) {
                $query->andWhere(['>=', 'created_at', $start]);
                $query->andWhere(['<=', 'created_at', $end]);
        }
        $info['total_complete_price'] = $query->sum('pay_price'); //总成交额
        $info['total_complete_price'] = $info['total_complete_price'] ?? 0;
        $info['select_order'] = $query->count(); //总成交订单数
        $order_ids = $query->select('id')->column();
        $info['sales'] = CommonOrderDetail::find()->where(['is_delete' => 0, 'status' => 1])->andWhere(['common_order_id' => $order_ids])->sum('num');
        $info['sales'] = $info['sales'] ?? 0;
        $info['buyer'] = $query->groupBy('user_id')->count(); //支付人数
        $info['buyer'] = $info['buyer'] ?? 0;
        if ($info['buyer'] == 0) {
            $info['single_price'] = 0;
        } else {
            $info['single_price'] = $info['total_complete_price'] / $info['buyer'];
        }


        if ($this->select_date) {
            if ($this->select_date == 1) {
                $info['new_user'] = User::find()->where(['mall_id' => $this->mall_id, 'is_delete' => 0])->andWhere(['>', 'created_at', $today])->count();
            }
            if ($this->select_date == 2) {
                $info['new_user'] = User::find()->where(['mall_id' => $this->mall_id, 'is_delete' => 0])->andWhere(['>', 'created_at', $month])->count();
            }
            if ($this->select_date == 3) {
                $info['new_user'] = User::find()->where(['mall_id' => $this->mall_id, 'is_delete' => 0])->andWhere(['>', 'created_at', $year])->count();
            }
        }

        if ($this->search_date) {
            $info['new_user'] = User::find()->where(['mall_id' => $this->mall_id, 'is_delete' => 0])->andWhere(['>', 'created_at', $start])->andWhere(['<', 'created_at', $end])->count();
        }

        $goods_list = Goods::find()
            ->where(['is_delete' => 0, 'mall_id' => $this->mall_id])
            ->andWhere(['>', 'sales', 0])
            ->orderBy('sales DESC')
            ->limit(10)
            ->select('name,cover_pic,sales')
            ->asArray()
            ->all();
        $user_list = CommonOrder::find()
            ->alias('c')
            ->innerJoin(['u' => User::tableName()], 'c.user_id=u.id')
            ->where(['c.is_delete' => 0, 'c.mall_id' => $this->mall_id,'c.is_pay'=>1])
            ->limit(10)
            ->select('sum(c.pay_price) as pay_price,u.nickname,u.avatar_url')
            ->groupBy('c.user_id')
            ->orderBy('pay_price desc')
            ->asArray()
            ->all();

        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['info' => $info, 'goods_list' => $goods_list, 'user_list' => $user_list]);
    }

}