<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-08
 * Time: 15:34
 */

namespace app\forms\mall\mall;


use app\core\ApiCode;
use app\helpers\CacheHelper;
use app\helpers\OptionHelper;
use app\helpers\SerializeHelper;
use app\models\BaseModel;
use app\models\DiyPage;

class PageEditForm extends BaseModel
{
    public $id;
    public $data;
    public $name;


    public function rules()
    {
        return [
            [['id'], 'integer'],
            [['data'], 'safe'],
            [['data'], 'string'],
            [['name'], 'string']
        ]; // TODO: Change the autogenerated stub
    }

    public function search()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $page = DiyPage::findOne(['is_delete' => 0, 'id' => $this->id, 'mall_id' => \Yii::$app->mall->id]);
        if (!$page) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '页面不存在!');
        }
        $page->data = SerializeHelper::decode($page->data);

        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['page' => $page]);
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $page = DiyPage::findOne(['is_delete' => 0, 'id' => $this->id, 'mall_id' => $this->mall_id]);
        if (!$page) {
            $page = new DiyPage();
            $page->mall_id = $this->mall_id;
        }
        $page->data = $this->data;
        $page->name = $this->name;
        if (!$page->save()) {
            return $this->responseErrorMsg($page);
        }
        if ($page->is_home) {
            OptionHelper::set('diy_home_name', $page->name, $this->mall_id);
            OptionHelper::set('diy_home', SerializeHelper::decode($page->data), $this->mall_id);
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功!');
    }

    public function delete()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $page = DiyPage::findOne(['is_delete' => 0, 'id' => $this->id, 'mall_id' => $this->mall_id]);
        if (!$page) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '页面不存在或已被删除!');
        }
        $page->is_delete = 1;
        if (!$page->save()) {
            return $this->responseErrorMsg($page);
        }

        return $this->apiResponse(ApiCode::CODE_SUCCESS, '删除成功');
    }

    public function setHome()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        DiyPage::updateAll(['is_home' => 0], ['is_delete' => 0, 'is_home' => 1, 'mall_id' => $this->mall_id]);
        $page = DiyPage::findOne(['is_delete' => 0, 'id' => $this->id, 'mall_id' => $this->mall_id]);
        if (!$page) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '页面不存在或已被删除!');
        }
        $page->is_home = 1;
        if (!$page->save()) {
            return $this->responseErrorMsg($page);
        }
        OptionHelper::set('diy_home_name', $page->name, $this->mall_id);
        OptionHelper::set('diy_home', SerializeHelper::decode($page->data), $this->mall_id);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '设置成功');
    }
}
