<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-12-21
 * Time: 23:46
 */

namespace app\forms\mall\mall;


use app\core\ApiCode;
use app\helpers\CacheHelper;
use app\helpers\ResponseHelper;
use app\helpers\SerializeHelper;
use app\models\BaseModel;

class PagePathForm extends BaseModel
{
    public $page;
    public $name;

    public function rules()
    {
        return [
            [['page', 'name'], 'string']
        ]; // TODO: Change the autogenerated stub
    }

    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $list = $this->getPathList();
        $h5Root = \Yii::$app->request->hostInfo . '/h5';
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'h5Root' => $h5Root, 'mall_id' => \Yii::$app->mall->id]);

    }


    private function getPathList()
    {

        $page_list = CacheHelper::get('page_list_' . \Yii::$app->mall->id);
        if ($page_list) {
            return $page_list;
        }


        $list = [
            ['name' => '首页', 'page' => '/pages/index/index'],
            ['name' => '个人中心', 'page' => '/pages/user/user'],
            ['name' => '商品详情', 'page' => '/pages/goods/goods'],
            ['name' => '领券中心', 'page' => '/pages/coupon/coupon'],
            ['name' => '商品列表', 'page' => '/pages/goods-list/goods-list'],
            ['name' => '分类', 'page' => '/pages/cat/cat'],
            ['name' => '订单列表', 'page' => '/pages/order/order'],
            ['name' => '订单详情', 'page' => '/pages/order-detail/order-detail'],
            ['name' => '提交订单', 'page' => '/pages/order-submit/order-submit'],
            ['name' => '收货地址', 'page' => '/pages/address/address'],
            ['name' => '地址编辑', 'page' => '/pages/address-edit/address-edit'],
            ['name' => '购物车', 'page' => '/pages/cart/cart'],
            ['name' => '订单支付', 'page' => '/pages/pay/pay'],
            ['name' => '搜索', 'page' => '/pages/search/search'],
            ['name' => '商品评价', 'page' => '/pages/comment/comment'],
            ['name' => '评价列表', 'page' => '/pages/comment-list/comment-list'],
            ['name' => '用户登录', 'page' => '/pages/login/login'],
            ['name' => '提交售后', 'page' => '/pages/refund/refund'],
            ['name' => '推广中心', 'page' => '/pages/manage/manage'],
            ['name' => '提现', 'page' => '/pages/cash/cash'],
            ['name' => '代理中心', 'page' => '/plugins/agency/agency'],
            ['name' => '积分记录', 'page' => '/pages/integral-log/integral-log'],
            ['name' => '余额记录', 'page' => '/pages/balance-log/balance-log'],
            ['name' => '账户设置', 'page' => '/pages/setting/setting'],
            ['name' => '关于我们', 'page' => '/pages/about/about'],
            ['name' => '提现记录', 'page' => '/pages/cash-log/cash-log'],
            ['name' => '佣金记录', 'page' => '/pages/price-log/price-log'],
        ];

        CacheHelper::set('page_list_' . \Yii::$app->mall->id, $list);

        return $list;

    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $list = $this->getPathList();

        foreach ($list as &$item) {

            if ($item['page'] == $this->page) {
                $item['name'] = $this->name;
            }
        }
        unset($item);

        CacheHelper::set('page_list_' . \Yii::$app->mall->id, $list);
        return ResponseHelper::send(ApiCode::CODE_SUCCESS, '保存成功');

    }

}