<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-12
 * Time: 22:43
 */

namespace app\forms\mall\mall;


use app\core\ApiCode;
use app\helpers\ImageHelper;
use app\helpers\OptionHelper;
use app\helpers\SerializeHelper;
use app\models\BaseModel;
use app\models\Tabbar;

class TabbarSettingForm extends BaseModel
{


    public $setting;
    public $color;

    public function rules()
    {
        return [
            [['color'], 'string'],
            [['setting'], 'safe']
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        $tabbar = Tabbar::findOne(['mall_id' => \Yii::$app->mall->id, 'is_delete' => 0]);
        if (!$tabbar) {
            $tabbar = new Tabbar();
            $tabbar->mall_id = \Yii::$app->mall->id;
        }
        $tabbar->attributes = $this->attributes;
        if (!$tabbar->save()) {
            return $this->responseErrorMsg($tabbar);
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }

    public function search()
    {
        $tabbar = Tabbar::findOne(['is_delete' => 0, 'mall_id' => \Yii::$app->mall->id]);
        if (!$tabbar) {
            $tabbar = new Tabbar();
            $tabbar->mall_id = \Yii::$app->mall->id;
            $tabbar->setting = SerializeHelper::encode([
                [
                    'name' => '首页',
                    'url' => '/pages/index/index',
                    'icon' => \Yii::$app->request->hostInfo . '/web/assets/default/tabbar/index.png',
                    'active_icon' => \Yii::$app->request->hostInfo . '/web/assets/default/tabbar/index-active.png',
                ],
                [
                    'name' => '分类',
                    'url' => '/pages/cat/cat',
                    'icon' => \Yii::$app->request->hostInfo . '/web/assets/default/tabbar/cat.png',
                    'active_icon' => \Yii::$app->request->hostInfo . '/web/assets/default/tabbar/cat-active.png',
                ],
                [
                    'name' => '购物车',
                    'url' => '/pages/cart/cart',
                    'icon' => \Yii::$app->request->hostInfo . '/web/assets/default/tabbar/cart.png',
                    'active_icon' => \Yii::$app->request->hostInfo . '/web/assets/default/tabbar/cart-active.png',
                ],
                [
                    'name' => '我的',
                    'url' => '/pages/user/user',
                    'icon' => \Yii::$app->request->hostInfo . '/web/assets/default/tabbar/my.png',
                    'active_icon' => \Yii::$app->request->hostInfo . '/web/assets/default/tabbar/my-active.png',
                ],
            ]);
            $tabbar->color = '#E41F19';
            $tabbar->save();
        }
        $tabbar->setting = SerializeHelper::decode($tabbar->setting);

        $userPageData = OptionHelper::get('user_page_data', \Yii::$app->mall->id);

        if (!$userPageData) {
            $userPageData = $this->getPageDefault();
        }


        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['tabbar' => $tabbar, 'user_page_data' => $userPageData]);
    }

    private function getPageDefault()
    {

        $default['header'] = [
            'user_bg' => ImageHelper::getUrl('/assets/default/user/user_bg.png'),
            'avatar' => ImageHelper::getUrl('/assets/default/user/avatar.png'),
            'goods' => [
                'is_show' => 1,
                'name' => '商品收藏'
            ],
            'shop' => [
                'is_show' => 1,
                'name' => '店铺收藏'
            ],
            'footmark' => [
                'is_show' => 1,
                'name' => '足迹'
            ],
        ];
        $default['order'] = [
            'status_0' => [
                'name' => '待付款',
                'url' => '/pages/order/order?status=0',
                'icon' => ImageHelper::getUrl('/assets/default/user/order0.png')
            ],
            'status_1' => [
                'name' => '待发货',
                'url' => '/pages/order/order?status=1',
                'icon' => ImageHelper::getUrl('/assets/default/user/order1.png')
            ],
            'status_2' => [
                'name' => '待收货',
                'url' => '/pages/order/order?status=2',
                'icon' => ImageHelper::getUrl('/assets/default/user/order2.png')
            ],
            'status_3' => [
                'name' => '待评价',
                'url' => '/pages/order/order?status=3',
                'icon' => ImageHelper::getUrl('/assets/default/user/order3.png')
            ],
            'status_4' => [
                'name' => '退款/售后',
                'url' => '/pages/order/order?status=4',
                'icon' => ImageHelper::getUrl('/assets/default/user/order4.png')
            ],
        ];

        $default['menus'] = [
            'name' => '常用工具',
            'type' => 0,
            'list' => [
                [
                    'name' => '待付款',
                    'url' => '/pages/order/order?status=0',
                    'icon' => ImageHelper::getUrl('/assets/default/user/order0.png')
                ],
                [
                    'name' => '待发货',
                    'url' => '/pages/order/order?status=1',
                    'icon' => ImageHelper::getUrl('/assets/default/user/order1.png')
                ],
                [
                    'name' => '待收货',
                    'url' => '/pages/order/order?status=2',
                    'icon' => ImageHelper::getUrl('/assets/default/user/order2.png')
                ],
                [
                    'name' => '待评价',
                    'url' => '/pages/order/order?status=3',
                    'icon' => ImageHelper::getUrl('/assets/default/user/order3.png')
                ],
                [
                    'name' => '退款/售后',
                    'url' => '/pages/order/order?status=4',
                    'icon' => ImageHelper::getUrl('/assets/default/user/order4.png')
                ],
            ]
        ];
        $default['finance'] = [
            'name' => '我的资产',
            'type' => 0,
            'integral' => [
                'name' => '积分',
                'is_show' => 1,
            ],
            'balance' => [
                'name' => '余额',
                'is_show' => 1,
            ],
            'price' => [

                'name' => '佣金',
                'is_show' => 1,
            ],
            'coupon' => [
                'name' => '优惠券',
                'is_show' => 1,
            ],

        ];
        return $default;

    }
}