<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-11-15
 * Time: 9:54
 */

namespace app\forms\mall\mall;


use app\core\ApiCode;
use app\helpers\OptionHelper;
use app\helpers\SerializeHelper;
use app\models\BaseModel;

class UploadSettingForm extends BaseModel
{

    public $oss;
    public $cos;
    public $qiniu;

    public function rules()
    {
        return [
            [['oss', 'qiniu', 'cos'], 'string']


        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }

        if ($this->oss) {

            OptionHelper::set('oss', SerializeHelper::decode($this->oss), \Yii::$app->mall->id);

        }
        if ($this->cos) {

            OptionHelper::set('cos', SerializeHelper::decode($this->cos), \Yii::$app->mall->id);

        }
        if ($this->qiniu) {

            OptionHelper::set('qiniu', SerializeHelper::decode($this->qiniu), \Yii::$app->mall->id);

        }

        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');


    }

    public function search()
    {
        $this->oss = OptionHelper::get('oss', \Yii::$app->mall->id);
        $this->qiniu = OptionHelper::get('qiniu', \Yii::$app->mall->id);
        $this->cos = OptionHelper::get('cos', \Yii::$app->mall->id);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', $this->attributes);
    }

}