<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-11-05
 * Time: 9:37
 */

namespace app\forms\mall\finance;


use app\core\ApiCode;
use app\helpers\OptionHelper;
use app\models\BaseModel;

class CashSettingForm extends BaseModel
{

    public $price;
    public $balance;

    public $other;

    public function rules()
    {
        return [

            [['price', 'balance','other'], 'safe']

        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $res = OptionHelper::set('cash_setting', $this->attributes, \Yii::$app->mall->id);
        if (!$res) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '保存失败');
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }

    public function search()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $res = OptionHelper::get('cash_setting', \Yii::$app->mall->id);
        if (!$res) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '未配置提现');
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['setting' => $res]);
    }
}