<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-11-02
 * Time: 13:30
 */

namespace app\forms\mall\finance;


use app\core\ApiCode;
use app\models\Admin;
use app\models\BaseModel;
use app\models\Cash;
use app\models\ChargeLog;
use app\models\PriceLog;
use app\models\User;

class ChargeListForm extends BaseModel
{
    public $page;
    public $limit;
    public $keyword;
    public $user_id;
    public $type;

    public function rules()
    {
        return [

            [['page', 'limit', 'user_id', 'type'], 'integer'],
            [['keyword'], 'string'],
            [['limit'], 'default', 'value' => 10]

        ]; // TODO: Change the autogenerated stub
    }


    public function getList()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $query = ChargeLog::find()
            ->alias('c')
            ->leftJoin(['u' => User::tableName()], 'u.id=c.user_id')
            ->andWhere(['c.is_delete' => 0, 'u.is_delete' => 0]);
        if ($this->type != '') {
            if ($this->type == 0) {
                $query->andWhere(['type' => 0]);
            }
            if ($this->type == 1) {
                $query->andWhere(['type' => 1]);
            }
        }
        if ($this->keyword) {
            $query->andWhere(['like', 'u.nickname', $this->keyword]);
        }
        $list = $query->page($pagination, $this->limit, $this->page)
            ->select('u.nickname,u.avatar_url,c.*')
            ->orderBy('c.created_at desc')
            ->asArray()->all();
        foreach ($list as &$item) {
            $item['created_at'] = date('Y-m-d H:i:s', $item['created_at']);
            $admin = Admin::findOne($item['admin_id']);
            if ($admin) {
                $item['admin'] = $admin->name;
            }else{
                $item['admin'] = '-';
            }
        }
        unset($item);
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['list' => $list, 'pagination' => $pagination]);

    }

}