<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-14
 * Time: 9:45
 */

namespace app\forms\mall\platform;


use app\core\ApiCode;
use app\helpers\ConstantHelper;
use app\helpers\OptionHelper;
use app\models\BaseModel;

class WechatForm extends BaseModel
{
    public $appid;
    public $secret;
    public $name;
    public $token;
    public $aes_key;
    public $auth_file;

    public function rules()
    {
        return [
            [['appid', 'secret', 'name'], 'trim'],
            [['appid'], 'string', 'max' => 64],
            [['secret', 'token', 'aes_key'], 'string', 'max' => 255],
            [['name'], 'string', 'max' => 45],
            [['auth_file'], 'string', 'max' => 128],
        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {

        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        if (!$this->appid || !$this->secret || !$this->name) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '请完善必填信息');
        }
        OptionHelper::set('platform_wechat', $this->attributes, \Yii::$app->mall->id);
        if ($this->appid) {
            OptionHelper::set($this->appid, ['platform' => ConstantHelper::PLATFORM_H5, 'mall_id' => $this->mall_id], \Yii::$app->mall->id);
        }

        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }


    public function search()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $wechat = OptionHelper::get('platform_wechat', \Yii::$app->mall->id);
        if (!$wechat) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '未配置微信');
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['wechat' => $wechat]);
    }


}