<?php
/**
 * @link:http://www.dujxmall.com/
 * @copyright: Copyright (c) 2020 广州动力宇宙信息科技
 * Created by PhpStorm
 * Author: ganxiaohao
 * Date: 2020-10-14
 * Time: 9:45
 */

namespace app\forms\mall\platform;


use app\core\ApiCode;
use app\helpers\ConstantHelper;
use app\helpers\OptionHelper;
use app\models\BaseModel;


class WxappForm extends BaseModel
{
    public $appid;
    public $secret;
    public $name;


    public function rules()
    {
        return [
            [['appid'], 'string', 'max' => 64],
            [['secret'], 'string', 'max' => 255],
            [['name'], 'string', 'max' => 45],

        ]; // TODO: Change the autogenerated stub
    }

    public function save()
    {

        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        if (!$this->appid || !$this->secret || !$this->name) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '请完善必填信息');
        }
        OptionHelper::set('platform_wxapp', $this->attributes, \Yii::$app->mall->id);
        if ($this->appid) {
            OptionHelper::set($this->appid, ['platform' => ConstantHelper::PLATFORM_APP, 'mall_id' => $this->mall_id], \Yii::$app->mall->id);
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '保存成功');
    }


    public function search()
    {
        if (!$this->validate()) {
            return $this->responseErrorInfo();
        }
        $wxapp = OptionHelper::get('platform_wxapp', \Yii::$app->mall->id);
        if (!$wxapp) {
            return $this->apiResponse(ApiCode::CODE_FAIL, '未配置APP');
        }
        return $this->apiResponse(ApiCode::CODE_SUCCESS, '', ['wxapp' => $wxapp]);
    }

    public function saveSettingByMallId($mall_id)
    {
        if (!$this->validate()) {
            return false;
        }

        return OptionHelper::set('platform_wxapp', $this->attributes, $mall_id);
        //return true;

    }
}
